---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossview-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: crossview-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-username
      remoteRef:
        key: crossview/credentials/genmachine
        property: admin-username
    - secretKey: admin-password
      remoteRef:
        key: crossview/credentials/genmachine
        property: admin-password
    - secretKey: db-password
      remoteRef:
        key: crossview/credentials/genmachine
        property: db-password
    - secretKey: session-secret
      remoteRef:
        key: crossview/credentials/genmachine
        property: session-secret
