---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &recoverCluster authentik-pgsql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: proxmox-retain
    size: 8Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: pgsql-basic-auth
  # bootstrap:
  #   recovery:
  #     source: *recoverCluster
  # backup:
  #   retentionPolicy: "15d"
  #   barmanObjectStore: &barmanObjectStore
  #     serverName: &currentCluster authentik-pgsql-recover
  #     destinationPath: s3://cnpg-backup/authentik/genmachine
  #     endpointURL: https://minio-api.talos-genmachine.fredcorp.com
  #     endpointCA:
  #       name: fredcorp-ca-chain
  #       key: fredcorp-ca-chain.pem
  #     s3Credentials:
  #       accessKeyId:
  #         name: restic-config
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: restic-config
  #         key: AWS_SECRET_ACCESS_KEY
  #     wal:
  #       compression: bzip2
  #     data:
  #       compression: bzip2
  # externalClusters:
  # - name: *recoverCluster
  #   barmanObjectStore:
  #     <<: *barmanObjectStore
  #     serverName: *recoverCluster
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgsql-basic-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: pgsql-basic-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik/pgsql
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik/pgsql
        property: password
