---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: proxmox-retain
    size: 8Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: pgsql-basic-auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgsql-basic-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: pgsql-basic-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik/pgsql
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik/pgsql
        property: password
