# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-authentik-pgsql-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: proxmox-retain
