# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: ServiceAccounts
entries:
  - model: authentik_core.user
    identifiers:
      name: sa-homarr
    attrs:
      attributes:
        goauthentik.io/user/token-expires: true
      is_active: true
      name: sa-homarr
      path: goauthentik.io/service-accounts
      type: service_account
      username: sa-homarr
  - model: authentik_core.user
    identifiers:
      username: sa-homepage
    attrs:
      is_active: true
      name: sa-homepage
      path: goauthentik.io/service-accounts
      type: service_account
      username: sa-homepage
      roles:
        - !Find [authentik_rbac.role, [name, homepage-readonly]]
