# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: genmachine-argocd
entries:
  - id: provider
    model: authentik_providers_oauth2.oauth2provider
    state: present
    identifiers:
      name: genmachine-argocd
    attrs:
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      client_type: confidential
      redirect_uris:
        - url: https://argocd.talos-genmachine.fredcorp.com/api/dex/callback
          matching_mode: strict
        - url: https://localhost:8085/auth/callback
          matching_mode: strict

      access_code_validity: minutes=1
      access_token_validity: hours=1
      refresh_token_validity: hours=2

      sub_mode: hashed_user_id
      property_mappings:
        - !Find [authentik_core.propertymapping, [name, "authentik default OAuth Mapping: OpenID 'openid'"]]
        - !Find [authentik_core.propertymapping, [name, "authentik default OAuth Mapping: OpenID 'profile'"]]
        - !Find [authentik_core.propertymapping, [name, "authentik default OAuth Mapping: OpenID 'email'"]]

  - id: application
    model: authentik_core.application
    state: present
    identifiers:
      name: genmachine-argocd
    attrs:
      name: genmachine-argocd
      group: Security
      meta_description: argocd
      provider: !Find [authentik_providers_oauth2.oauth2provider, [name, genmachine-argocd]]
      policy_engine_mode: any
      slug: genmachine-argocd
