---
proxmox-csi-plugin:
  createNamespace: false
  priorityClassName: system-cluster-critical
  node:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

  nodeSelector:
    node-role.kubernetes.io/control-plane: ''
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule

  storageClass:
    - name: proxmox-retain
      storage: local-lvm
      reclaimPolicy: Retain
    - name: proxmox-delete
      storage: local-lvm
      reclaimPolicy: Retain
