---
kubelet-csr-approver:
  image:
    repository: ghcr.io/postfinance/kubelet-csr-approver
    pullPolicy: IfNotPresent
    tag: 'v1.2.6@sha256:223c497ef54104f141a88e2569c195009c523a498ccffb2f3cbde62d03c72d44'
