---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  encrypt:
    desc: Encrypt all SOPS files (safe, idempotent)
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    env:
      SOPS_AGE_KEY_FILE: age.key
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: {var: SECRET_FILES}
        cmd: |
          echo "Encrypting {{ .ITEM }}"
          if grep -q 'ENC\[' {{ .ITEM }}; then
            echo "🔒 already encrypted: {{ .ITEM }}"
            continue
          else
            if sops encrypt --in-place "{{ .ITEM }}"; then
              echo "✅ Successfully encrypted {{ .ITEM }}"
            else
              echo "❌ Error encrypting {{ .ITEM }}" >&2
            fi
          fi

  decrypt:
    desc: Decrypt all SOPS files (safe)
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    env:
      SOPS_AGE_KEY_FILE: age.key
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: {var: SECRET_FILES}
        cmd: |
          echo "Decrypting {{ .ITEM }}"
          if grep -q 'ENC\[' {{ .ITEM }}; then
            if sops decrypt --in-place "{{ .ITEM }}"; then
              echo "✅ Successfully decrypted {{ .ITEM }}"
            else
              echo "❌ Error decrypting {{ .ITEM }}" >&2
            fi
          else
            echo "🟢 File {{ .ITEM }} is already decrypted, skipping."
          fi

  vault:encrypt:
    desc: Decrypt SOPS files using AGE key from Vault
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: {var: SECRET_FILES}
        cmd: |
          echo "Encrypting {{ .ITEM }}"
          echo "🔓 Fetching AGE public key from Vault..."
          SOPS_AGE_KEY=$(vault kv get -address={{ .VAULT_ENDPOINT }} -field=public-key admin/sops/age)
          if grep -q 'ENC\[' {{ .ITEM }}; then
            echo "🔒 already encrypted: {{ .ITEM }}"
            continue
          else
            if sops encrypt --in-place "{{ .ITEM }}"; then
              echo "✅ Successfully encrypted {{ .ITEM }}"
            else
              echo "❌ Error encrypting {{ .ITEM }}" >&2
            fi
          fi

  vault:decrypt:
    desc: Decrypt SOPS files using AGE key from Vault
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: {var: SECRET_FILES}
        cmd: |
          echo "Decrypting {{ .ITEM }}"
          echo "🔓 Fetching AGE secret key from Vault..."
          SOPS_AGE_KEY=$(vault kv get -address={{ .VAULT_ENDPOINT }} -field=private-key admin/sops/age)
          echo "key $SOPS_AGE_KEY"
          if grep -q 'ENC\[' {{ .ITEM }}; then
            if sops decrypt --in-place "{{ .ITEM }}"; then
              echo "✅ Successfully decrypted {{ .ITEM }}"
            else
              echo "❌ Error decrypting {{ .ITEM }}" >&2
            fi
          else
            echo "🟢 File {{ .ITEM }} is already decrypted, skipping."
          fi

  check-encryption:
    desc: Verify that all sops files are encrypted
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: {var: SECRET_FILES}
        cmd: |
          echo "Checking encryption for {{ .ITEM }}..."
          if grep -q 'ENC\[' "{{ .ITEM }}"; then
            echo "✅ {{ .ITEM }} is encrypted."
          else
            echo "❌ {{ .ITEM }} is NOT encrypted!" >&2
            exit 1
          fi
