---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard-data
  namespace: adguard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-retain
