---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: genmachine-wildcard
spec:
  commonName: '*.talos-genmachine.fredcorp.com'
  dnsNames:
    - '*.talos-genmachine.fredcorp.com'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: genmachine-wildcard
  usages:
    - digital signature
    - key encipherment
