---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-k0s
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  project: infra-security
  source:
    path: k0s-home/manifests/authentik
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true