---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-hydrator-fullstack
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: github-app-hydrator-fullstack
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository-write
      data:
        url: https://github.com/ixxeL-DevOps/fullstack.git
        type: git
        githubAppID: '{{ .appid }}'
        githubAppInstallationID: '{{ .installid }}'
        githubAppPrivateKey: |-
          {{ .privatekey }}
  data:
  - secretKey: appid
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_ID
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: installid
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_INSTALL_ID
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: privatekey
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_PRIVATE_KEY
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-repocreds
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: github-app-repocreds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com
        type: git
        githubAppID: '{{ .appid }}'
        githubAppInstallationID: '{{ .installid }}'
        githubAppPrivateKey: |-
          {{ .privatekey }}
  data:
  - secretKey: appid
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_ID
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: installid
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_INSTALL_ID
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: privatekey
    remoteRef:
      key: github
      property: GH_APP_ARGOCD_PRIVATE_KEY
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
