---
minio:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-07-23T15-54-02Z
    pullPolicy: IfNotPresent
  mcImage:
    repository: quay.io/minio/mc
    tag: RELEASE.2025-07-21T05-28-08Z
    pullPolicy: IfNotPresent

  mode: standalone
  existingSecret: 'minio-creds'
  # rootUser: "minio"
  # rootPassword: "minio123"

  tls:
    enabled: false

  persistence:
    enabled: true
    annotations:
    existingClaim: 'pvc-minio'
    storageClass: 'nfs-csi-retain'
    volumeName: 'minio'
    accessMode: ReadWriteOnce
    size: 50Gi

  ingress:
    enabled: true
    ingressClassName: 'traefik'
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: minio-api.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    path: /
    hosts:
      - minio-api.talos-genmachine.fredcorp.com
    tls:
      - secretName: minio-api-tls-cert
        hosts:
          - minio-api.talos-genmachine.fredcorp.com

  consoleIngress:
    enabled: true
    ingressClassName: 'traefik'
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: minio.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    path: /
    hosts:
      - minio.talos-genmachine.fredcorp.com
    tls:
      - secretName: minio-tls-cert
        hosts:
          - minio.talos-genmachine.fredcorp.com

  buckets:
    - name: cnpg-backup
      # Policy to be set on the
      # bucket [none|download|upload|public]
      policy: none
      # Purge if bucket exists already
      purge: false
      # set versioning for
      # bucket [true|false]
      versioning: true # remove this key if you do not want versioning feature
      # set objectlocking for
      # bucket [true|false] NOTE: versioning is enabled by default if you use locking
      objectlocking: false

  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus

  oidc:
    enabled: false
    configUrl: 'https://authentik.talos-genmachine.fredcorp.com/application/o/genmachine-minio/'
    existingClientSecretName: 'oidc-minio'
    existingClientIdKey: 'client-id'
    existingClientSecretKey: 'client-secret'
    claimName: 'policy'
    scopes: 'openid,profile,email'
    redirectUri: 'https://minio.talos-genmachine.fredcorp.com/oauth_callback'
    displayName: 'OIDC Authentik'
