# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-homarr-data
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: proxmox-data
