---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: restore-homarr-db
spec:
  trigger:
    manual: restore-once
  restic:
    customCA:
      secretName: fredcorp-ca-chain
      key: fredcorp-ca-chain.pem
    repository: restic-config
    # Use an existing PVC, don't provision a new one
    destinationPVC: homarr-database
    copyMethod: Direct
    storageClassName: nfs-csi-delete
