---
# Area
- name: area/github
  color: '72ccf3'
  description: >-
    Changes made in the github directory
- name: area/infra
  color: '72ccf3'
  description: >-
    Changes made in the infra directory
- name: area/gitops
  color: '72ccf3'
  description: >-
    Changes made in the gitops directory
- name: area/taskfile
  color: '72ccf3'
  description: >-
    Changes made in the taskfile directory
- name: env/genmachine
  color: '0636CF'
  description: >-
    Changes made in the Talos cluster
- name: env/beelink
  color: '0636CF'
  description: >-
    Changes made in the k0s cluster
# Renovate
- name: renovate/docker
  color: '006B75'
  description: >-
    Changes related to docker image update
- name: renovate/github-action
  color: '006B75'
  description: >-
    Changes related to GitHub Actions update
- name: renovate/github-release
  color: '006B75'
  description: >-
    Changes related to GitHub tag/release update
- name: renovate/grafana-dashboard
  color: '006B75'
  description: >-
    Changes related to Grafana dashboard update
- name: renovate/helm
  color: '006B75'
  description: >-
    Changes related to Helm Chart update
# Semantic Type
- name: type/digest
  color: 'ffec19'
- name: type/patch
  color: '4E911C'
- name: type/minor
  color: 'ff9800'
- name: type/major
  color: 'f6412d'
# apps
- name: app/adguard
  color: '66B574'
  description: >-
    Changes made to AdGuard application
- name: app/argocd
  color: 'FF6E00'
  description: >-
    Changes made to ArgoCD application
- name: app/authentik
  color: 'FD4B2D'
  description: >-
    Changes made to Authentik application
- name: app/cilium
  color: 'F8C517'
  description: >-
    Changes made to Cilium application
- name: app/coredns
  color: '5F259F'
  description: >-
    Changes made to CoreDNS application
- name: app/csi-driver-nfs
  color: '00366B'
  description: >-
    Changes made to CSI Driver NFS application
- name: app/external-secrets
  color: '121212'
  description: >-
    Changes made to External Secrets application
- name: app/gha-arc-controller
  color: '24292E'
  description: >-
    Changes made to GitHub ARC controller application
- name: app/homarr
  color: 'CF300C'
  description: >-
    Changes made to Homarr application
- name: app/loki
  color: 'FFE000'
  description: >-
    Changes made to Loki application
- name: app/minio
  color: '061729'
  description: >-
    Changes made to Minio application
- name: app/prometheus
  color: 'F45B04'
  description: >-
    Changes made to Prometheus application
- name: app/proxmox-csi-plugin
  color: 'F45B04'
  description: >-
    Changes made to Proxmox CSI plugin application
- name: app/spegel
  color: '677872'
  description: >-
    Changes made to Spegel application
- name: app/stakater
  color: '5A6CE5'
  description: >-
    Changes made to Stakater application
- name: app/traefik
  color: '27A2DB'
  description: >-
    Changes made to Traefik application
- name: app/system-upgrade-controller
  color: '4E0DA8'
  description: >-
    Changes made to System Upgrade Controller application
- name: app/vault
  color: '0B0D06'
  description: >-
    Changes made to HashiCorp Vault application
- name: app/wireguard
  color: '8B0000'
  description: >-
    Changes made to Wireguard application
# Uncategorized
- name: bug
  color: 'd73a4a'
- name: docs
  color: '0075ca'
- name: do-not-merge
  color: 'ee0701'
- name: enhancement
  color: 'a2eeef'
- name: link-checker
  color: '7b55d7'
- name: question
  color: 'd876e3'
- name: wontfix
  color: 'ffffff'
