---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: minio-creds
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio/creds/admin
        property: user
    - secretKey: rootPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio/creds/admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: oidc-minio
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio/oidc/genmachine
        property: client-id
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio/oidc/genmachine
        property: client-secret
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: minio-creds
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: admin
#     kind: ClusterSecretStore
#   target:
#     name: minio-creds
#     creationPolicy: Owner
#     template:
#       type: Opaque
#       data:
#         config.env: |
#           '{{ "{{" }}printf "export MINIO_ROOT_USER=\"%s\"\nexport MINIO_ROOT_PASSWORD=\"%s\"" .user .password{{ "}}" }}'
#   data:
#     - secretKey: user
#       remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None
#         key: minio/creds/admin
#         property: user
#     - secretKey: password
#       remoteRef:
#         conversionStrategy: Default
#         decodingStrategy: None
#         metadataPolicy: None
#         key: minio/creds/admin
#         property: password
