---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: minio
      csi.storage.k8s.io/pvc/name: pvc-minio
      server: 192.168.1.250
      share: /volatile
      subdir: minio
    volumeHandle: 192.168.1.250#volatile#minio##
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-retain
  mountOptions:
    - nfsvers=4.1
    - nolock
