---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: false

exclude: |
  (?x)^(
      gitops/local-storage/.*
  )$

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        language: script
        args: [--severity=error]
        additional_dependencies: []

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
      - id: remove-crlf

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args:
          - -conf
          - .yamlfmt

  - repo: local
    hooks:
      - id: sops-check-encryption
        name: SOPS check-encryption
        entry: bash -c "task sops:check-encryption"
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: prettier
        name: Prettier linting
        entry: bash -c "task lint:all"
        language: system
