---
site_name: ixxeL-DevOps HomeLab
site_author: ixxeL2097
site_description: >-
  My personal HomeLab
repo_name: !ENV [REPO_NAME, 'ixxeL-DevOps/fullstack']
repo_url: !ENV [REPO_URL, 'https://github.com/ixxeL-DevOps/fullstack']
extra_css:
  - stylesheets/extra.css
theme:
  favicon: assets/k8s-home.png
  font:
    text: Work Sans
  logo: assets/k8s-home.png
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      # Palette toggle for automatic mode
      # - media: "(prefers-color-scheme)"
      #   toggle:
      #     icon: material/brightness-auto
      #     name: Switch to light mode
      # # Palette toggle for light mode
      # - media: "(prefers-color-scheme: light)"
      #   scheme: default
      #   toggle:
      #     icon: material/brightness-7
      #     name: Switch to dark mode
      # # Palette toggle for dark mode
      # - media: "(prefers-color-scheme: dark)"
      #   scheme: slate
      #   toggle:
      #     icon: material/brightness-4
      #     name: Switch to system preference
  features:
    # - navigation.top
    - toc.integrate
    - navigation.tabs
    # - navigation.sections
    # - navigation.tracking
    - navigation.expand
    - navigation.instant
    - search.suggest
    - content.code.copy
    - content.tooltips
    - content.code.wrap
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - codehilite:
      css_class: highlight

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      timezone: UTC
      locale: en
      enable_creation_date: true
      exclude:
        - index.md

nav:
  - Documentation:
      - Cluster:
          - K0S: cluster/k0s.md
          - Talos: cluster/talos.md
      - GitOps:
          - ArgoCD: argocd/argocd.md
      - TLS/HTTPS:
          - Certmanager: certificates/certmanager.md
          - Encryption: certificates/tls.md
      - Authentication:
          - OIDC: authentication/oidc.md
          - Auth Forwarding: authentication/proxy-auth.md
      - Networking:
          - Cilium: network/cilium.md
      - Storage:
          - Proxmox-CSI: storage/csi-promox.md
      - Secrets:
          - ESO: secrets/externalsecrets.md
      - VPN:
          - Cluster config: VPN/wireguard.md
      - Encryption:
          - SOPS: encryption/sops.md
  - Home: index.md
