---
site_name: ixxeL-DevOps HomeLab
site_author: ixxeL2097
site_description: >-
  My personal HomeLab
repo_name: !ENV [REPO_NAME, 'ixxeL-DevOps/fullstack']
repo_url: !ENV [REPO_URL, 'https://github.com/ixxeL-DevOps/fullstack']
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@10.0.0/dist/mermaid.min.js
  - javascripts/mermaid.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ixxeL-DevOps/fullstack
    - icon: fontawesome/solid/book
      link: https://ixxel-devops.github.io/fullstack/
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      timezone: UTC
      locale: en
      enable_creation_date: true
      exclude:
        - index.md
  - git-committers:
      repository: ixxeL-DevOps/fullstack
      branch: main
      exclude:
        - index.md
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: contribution
      authorship_threshold_percent: 10
      exclude:
        - index.md

theme:
  favicon: assets/k8s-home.png
  font:
    text: Work Sans
  logo: assets/k8s-home.png
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      # Palette toggle for automatic mode
      # - media: "(prefers-color-scheme)"
      #   toggle:
      #     icon: material/brightness-auto
      #     name: Switch to light mode
      # # Palette toggle for light mode
      # - media: "(prefers-color-scheme: light)"
      #   scheme: default
      #   toggle:
      #     icon: material/brightness-7
      #     name: Switch to dark mode
      # # Palette toggle for dark mode
      # - media: "(prefers-color-scheme: dark)"
      #   scheme: slate
      #   toggle:
      #     icon: material/brightness-4
      #     name: Switch to system preference
  features:
    # - navigation.top
    - navigation.tabs
    # - navigation.sections
    # - navigation.tracking
    - navigation.expand
    - navigation.instant
    - search.suggest
    - content.code.copy
    - content.tooltips
    - content.code.wrap
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - codehilite:
      css_class: highlight

nav:
  - Documentation:
      - Cluster:
          - K0S: cluster/k0s.md
          - New Cluster Provisioning: NEW_CLUSTER_PROVISIONING.md
      - GitOps:
          - ArgoCD: argocd/argocd.md
          - ArgoCD Application Deployment: ARGOCD_APPLICATION_DEPLOYMENT_GUIDE.md
      - TLS/HTTPS:
          - Certmanager: certificates/certmanager.md
          - Encryption: certificates/tls.md
      - Authentication:
          - OIDC: authentication/oidc.md
          - Auth Forwarding: authentication/proxy-auth.md
      - VPN:
          - Cluster config: VPN/wireguard.md
      - Complete Platform Guide: FULL_DOCUMENTATION.md
      - Mermaid Test: mermaid-test.md
  - Repository:
      - Git Summary: git-summary.md
  - Home: index.md
