---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
set:
  - pipefail
shopt:
  - globstar

silent: true

vars:
  K0S_ROOT: '{{.ROOT_DIR}}/infra/k0s'
  TALOS_ROOT: '{{.ROOT_DIR}}/infra/talos'
  GITOPS_ROOT: '{{.ROOT_DIR}}/gitops'
  MKDOCS_DOCS_ROOT: '{{.ROOT_DIR}}/docs'
  MKDOCS_CFG: '{{.ROOT_DIR}}/mkdocs.yml'
  VAULT_ENDPOINT: 'https://vault.talos-genmachine.fredcorp.com'
  K8S_API: 'talos-cluster.genmachine.fredcorp.com'
  MINIO_API: 'minio-api.talos-genmachine.fredcorp.com'

includes:
  k0s: .taskfiles/k0s
  pre-commit: .taskfiles/pre-commit
  mkdocs: .taskfiles/mkdocs
  eso: .taskfiles/eso
  talos: .taskfiles/talos
  sops: .taskfiles/sops
  proxmox: .taskfiles/proxmox
  bootstrap: .taskfiles/bootstrap/talos
  lint: .taskfiles/lint
  k8s: .taskfiles/kubernetes
  vault: .taskfiles/vault
  helm: .taskfiles/helm
  restic: .taskfiles/restic

tasks:
  default:
    silent: true
    cmd: task -l

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
