---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
set:
  - pipefail
shopt:
  - globstar

silent: true

vars:
  K0S_ROOT: "{{.ROOT_DIR}}/infra/k0s"
  TALOS_ROOT: "{{.ROOT_DIR}}/infra/talos"
  GITOPS_ROOT: "{{.ROOT_DIR}}/gitops"
  MKDOCS_DOCS_ROOT: "{{.ROOT_DIR}}/docs"
  MKDOCS_CFG: "{{.ROOT_DIR}}/mkdocs.yml"

includes:
  k0s: .taskfiles/k0s
  pre-commit: .taskfiles/pre-commit
  mkdocs: .taskfiles/mkdocs
  eso: .taskfiles/eso
  talos: .taskfiles/talos
  sops: .taskfiles/sops
  proxmox: .taskfiles/proxmox
  bootstrap: .taskfiles/bootstrap/talos

tasks:
  default:
    silent: true
    cmd: task -l

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
