---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-range
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.191-192.168.1.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-range
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-range
