# yamllint disable
---
{{ if .Values.ipamIpPool.enabled }}
apiVersion: 'cilium.io/v2alpha1'
kind: CiliumLoadBalancerIPPool
metadata:
  name: local-pool
  namespace: {{ .Release.Namespace }}
spec:
  blocks:
    - start: {{ .Values.ipamIpPool.start | squote }}
      stop: {{ .Values.ipamIpPool.stop | squote }}
{{ end }}
