---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infra-apps-priority
value: 900000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Priority class for infrastructure workloads, lower than critical system pods."
