---
uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    pullPolicy: IfNotPresent
    tag: '1.23.16-debian@sha256:431fee3be822b04861cf0e35daf4beef6b7cb37391c5f26c3ad6e12ce280fe18'

  ingress:
    enabled: true
    className: 'traefik'
    annotations: {}
    hosts:
      - host: uptime-kuma.k0s-fullstack.fredcorp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
