---
ipamIpPool:
  enabled: true
  start: '192.168.1.160'
  stop: '192.168.1.200'

cilium:
  image:
    repository: 'quay.io/cilium/cilium'
    tag: v1.19.4
    pullPolicy: 'IfNotPresent'

  hubble:
    enabled: true
    metrics:
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - port-distribution
        - httpV2
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: fredcorp-ca
          cert-manager.io/common-name: hubble.talos-genmachine.fredcorp.com
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - hubble.talos-genmachine.fredcorp.com
        tls:
          - hosts:
              - hubble.talos-genmachine.fredcorp.com
            secretName: hubble-tls-cert

  envoy:
    enabled: false

  routingMode: native
  autoDirectNodeRoutes: true
  ipv4NativeRoutingCIDR: '10.244.0.0/16'

  enableIPv4BIGTCP: true

  encryption:
    enabled: true
    type: wireguard
    nodeEncryption: false

  # Egress test
  egressGateway:
    enabled: true
  bpf:
    masquerade: true

  operator:
    image:
      repository: 'quay.io/cilium/operator'
      tag: v1.19.4
      pullPolicy: 'IfNotPresent'

    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
