cilium:
  image:
    repository: 'quay.io/cilium/cilium'
    tag: 'v1.17.1'
    pullPolicy: 'IfNotPresent'

  hubble:
    enabled: false
    ui:
      enabled: false
    relay:
      enabled: false

  envoy:
    enabled: false
    image:
      repository: 'quay.io/cilium/cilium-envoy'
      tag: 'v1.31.5-1739264036-958bef243c6c66fcfd73ca319f2eb49fff1eb2ae'
      pullPolicy: 'IfNotPresent'

  operator:
    image:
      repository: 'quay.io/cilium/operator'
      tag: 'v1.17.1'
      pullPolicy: 'IfNotPresent'

  # prometheus:
  #   enabled: true
  #   serviceMonitor:
  #     enabled: true
  #     labels:
  #       release: prom-stack-talos
  # operator:
  #   prometheus:
  #     enabled: true
  #     serviceMonitor:
  #       enabled: true
  #       labels:
  #         release: prom-stack-talos
