---
ipamIpPool:
  enabled: true
  start: '192.168.1.160'
  stop: '192.168.1.170'

cilium:
  image:
    repository: 'quay.io/cilium/cilium'
    tag: v1.17.2
    pullPolicy: 'IfNotPresent'

  hubble:
    enabled: false
    ui:
      enabled: false
    relay:
      enabled: false

  envoy:
    enabled: false

  operator:
    image:
      repository: 'quay.io/cilium/operator'
      tag: v1.17.2
      pullPolicy: 'IfNotPresent'
