---
ipamIpPool:
  enabled: true
  start: '192.168.1.160'
  stop: '192.168.1.170'

cilium:
  image:
    repository: 'quay.io/cilium/cilium'
    pullPolicy: 'IfNotPresent'

  hubble:
    enabled: false
    ui:
      enabled: false
    relay:
      enabled: false

  envoy:
    enabled: false
    image:
      repository: 'quay.io/cilium/cilium-envoy'
      pullPolicy: 'IfNotPresent'

  operator:
    image:
      repository: 'quay.io/cilium/operator'
      pullPolicy: 'IfNotPresent'
