---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.message.format.version: "3.6"
      inter.broker.protocol.version: "3.6"
      # Optimisations performance
      num.network.threads: 8
      num.io.threads: 16
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    storage:
      type: persistent-claim
      size: 10Gi
      class: nfs-csi-delete
      deleteClaim: true
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    storage:
      type: persistent-claim
      size: 10Gi
      class: nfs-csi-delete
      deleteClaim: false
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
  entityOperator:
    topicOperator: {}
    userOperator: {}