---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders
  labels:
    strimzi.io/cluster: kafka-cluster  # Nom de votre cluster Kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000     # 7 jours de rétention
    cleanup.policy: delete      # Supprime les anciens messages
    compression.type: snappy    # Compression des messages
    min.insync.replicas: 2      # Minimum 2 réplicas synchronisés
