---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /gitops/core/**
    argocd-diff-preview/watch-pattern: '/gitops/core/.*'
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  sources:
    - path: gitops/core/apps/beelink
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/appProjects
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/repos
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/clusters/beelink
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jqPathExpressions:
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 6
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
