---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../blueprints
    argocd-diff-preview/watch-pattern: 'gitops/manifests/authentik/app/.*, gitops/manifests/authentik/blueprints/.*'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  project: infra-security
  sources:
    - path: gitops/manifests/authentik/app
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/manifests/authentik/blueprints
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
