---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../../common;../blueprints
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  project: infra-security
  sources:
    - path: gitops/manifests/authentik/beelink/app
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/gitops/manifests/authentik/common/common-values.yaml
          - $values/gitops/manifests/authentik/beelink/app/beelink-values.yaml
    - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      ref: values
    - path: gitops/manifests/authentik/beelink/blueprints
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
