---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-beelink
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd-diff-preview/watch-pattern: 'gitops/manifests/external-secrets/.*'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: infra-security
  sources:
    - path: gitops/manifests/external-secrets/beelink
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/gitops/manifests/external-secrets/values/common-values.yaml
          - $values/gitops/manifests/external-secrets/beelink/beelink-values.yaml
    - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        bundle.chain/inject: 'enabled'
