---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd-diff-preview/watch-pattern: 'gitops/manifests/metallb/.*'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: infra-network
  sources:
    - path: gitops/manifests/metallb/beelink
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/gitops/manifests/metallb/values/common-values.yaml
          - $values/gitops/manifests/metallb/beelink/beelink-values.yaml
    - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
