---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
    argocd-diff-preview/watch-pattern: 'gitops/manifests/traefik/k0s/.*, gitops/manifests/traefik/values/.*'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: infra-network
  sources:
    - path: gitops/manifests/traefik/k0s
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/gitops/manifests/traefik/values/common-values.yaml
          - $values/gitops/manifests/traefik/k0s/k0s-values.yaml
    - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  ignoreDifferences:
    - group: traefik.io
      kind: IngressRoute
      jqPathExpressions:
        - .metadata.annotations
