    services:
      adminPanel:
        type: ClusterIP
        port: 3000
      http:
        type: ClusterIP
        port: 80
      https:
        enabled: true
        type: ClusterIP
        port: 443
      dns:
        enabled: true
        type: NodePort
        externalTrafficPolicy:
        loadBalancerIP:
        tcp:
          port: 53
          nodePort:
        udp:
          port: 53
          nodePort:
      dnsOverTls:
        enabled: true
        type: NodePort
        loadBalancerIP:
        port: 853
      dnsOverQuic:
        enabled: true
        type: NodePort
        port1:
          port: 784
          nodePort:
        port2:
          port: 8853
          nodePort:
        externalTrafficPolicy:
        loadBalancerIP:
      dnscrypt:
        enabled: true
        type: NodePort
        externalTrafficPolicy:
        loadBalancerIP:
        tcp:
          port: 5443
          nodePort:
        udp:
          port: 5443
          nodePort:

    ingresses:
      adminPanel:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard-admin.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: adguard-admin-tls
        #    hosts:
        #      - adguard-admin.fullstack.fredcorp.com
      http:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - adguard.fullstack.fredcorp.com
      https:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard-secure.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: adguard-secure-tls
        #    hosts:
        #      - adguard-secure.fullstack.fredcorp.com

    persistence:
      existingClaim: pvc-adguard-data
      volumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

    bootstrapEnabled: false