---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/lib/rancher/k3s/storage/vault-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3d-home-server-0
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-vault-data
#   namespace: vault
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: local-path
#   volumeName: pv-vault-data
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: kube-system
spec:
  targetNamespace: vault
  createNamespace: true
  version: 0.29.1
  chart: vault
  repo: https://helm.releases.hashicorp.com
  valuesContent: |-
    global:
      enabled: true

    injector:
      enabled: false

    server:
      enabled: true
      dataStorage:
        enabled: true
        size: 10Gi
        mountPath: "/vault/data"
        storageClass: local-path
        accessMode: ReadWriteOnce

      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain

      ingress:
        enabled: true
        labels: {}
        annotations: {}
        ingressClassName: "traefik"
        pathType: Prefix
        activeService: true
        hosts:
          - host: vault.fullstack.fredcorp.com
            paths: []
        tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - chart-example.local

    standalone:
      enabled: true
      config: |-
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }

    ui:
      enabled: true
      publishNotReadyAddresses: true
      activeVaultPodOnly: false
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200
      targetPort: 8200