---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  local:
    path: /home/fred/git/github/ixxeL-GitOps/fullstack/k0s-home/local-storage/vault-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3d-home-server-0