---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /gitops/core/apps/genmachine/storage;/gitops/core/apps/genmachine/system-upgrade;/gitops/core/apps/genmachine/kube-system;/gitops/core/apps/genmachine/infra;/gitops/core/apps/genmachine/system;/gitops/core/apps/genmachine/observability;/gitops/core/appProjects;/gitops/core/repos;/gitops/core/clusters/genmachine
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  sources:
    - path: gitops/core/apps/genmachine/argo
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/kube-system
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/infra
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/observability
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/storage
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/system
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/apps/genmachine/system-upgrade
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/appProjects
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/repos
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/clusters/genmachine
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - Validate=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 6
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
