---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd-diff-preview/watch-pattern: 'gitops/bootstrap/genmachine/.*'
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: gitops/bootstrap/genmachine
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
    helm:
      releaseName: argocd
      valueFiles:
        - genmachine-values.yaml
      ignoreMissingValueFiles: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 6
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        bundle.chain/inject: 'enabled'
