---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  setup:
    desc: Setup environment variables
    cmds:
      - |
        echo "Fetching Minio creds from Vault..."
        export MINIO_ROOT_USER=$(vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.user')
        export MINIO_ROOT_PASSWORD=$(vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.password')
        export RESTIC_REPOSITORY=s3:https://{{.MINIO_API}}/restic
        export RESTIC_PASSWORD=$(vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/restic/repo/minio-backup | jq -r '.data.data.password')
        echo "✅ Credentials exported successfully"

  stats:
    desc: Display restic repo stats
    vars:
      MINIO_ROOT_USER:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.user'
      MINIO_ROOT_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.password'
      RESTIC_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/restic/repo/minio-backup | jq -r '.data.data.password'
    env:
      MINIO_ROOT_USER: '{{.MINIO_ROOT_USER}}'
      MINIO_ROOT_PASSWORD: '{{.MINIO_ROOT_PASSWORD}}'
      RESTIC_PASSWORD: '{{.RESTIC_PASSWORD}}'
    cmds:
      - restic stats -r s3:https://{{.MINIO_API}}/restic/volsync/vault/genmachine

  check:
    desc: Check repo for errors
    vars:
      MINIO_ROOT_USER:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.user'
      MINIO_ROOT_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.password'
      RESTIC_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/restic/repo/minio-backup | jq -r '.data.data.password'
    env:
      MINIO_ROOT_USER: '{{.MINIO_ROOT_USER}}'
      MINIO_ROOT_PASSWORD: '{{.MINIO_ROOT_PASSWORD}}'
      RESTIC_PASSWORD: '{{.RESTIC_PASSWORD}}'
    cmds:
      - restic check -r s3:https://{{.MINIO_API}}/restic/volsync/vault/genmachine

  forget:
    desc: Froget/Clean
    vars:
      MINIO_ROOT_USER:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.user'
      MINIO_ROOT_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/minio/creds/admin | jq -r '.data.data.password'
      RESTIC_PASSWORD:
        sh: vault kv get -format=json -tls-skip-verify -address={{.VAULT_ENDPOINT}} admin/restic/repo/minio-backup | jq -r '.data.data.password'
    env:
      MINIO_ROOT_USER: '{{.MINIO_ROOT_USER}}'
      MINIO_ROOT_PASSWORD: '{{.MINIO_ROOT_PASSWORD}}'
      RESTIC_PASSWORD: '{{.RESTIC_PASSWORD}}'
    cmds:
      - restic forget -r s3:https://{{.MINIO_API}}/restic/volsync/adguard/genmachine --prune --keep-last 5 -v
