---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-game-config
  labels:
    app: vrising
data:
  ServerGameSettings.json: |
    {
      "GameDifficulty": "Normal",
      "GameModeType": "PvP",
      "CastleDamageMode": "Never",
      "SiegeWeaponHealth": "Normal",
      "PlayerDamageMode": "Always",
      "CastleHeartDamageMode": "CanBeDestroyedByPlayers",
      "PvPProtectionMode": "Medium",
      "DeathContainerPermission": "Anyone",
      "RelicSpawnType": "Unique",
      "CanLootEnemyContainers": true,
      "BloodBoundEquipment": true,
      "TeleportBoundItems": true,
      "BatBoundItems": false,
      "AllowGlobalChat": true,
      "AllWaypointsUnlocked": true,
      "FreeCastleRaid": false,
      "FreeCastleClaim": false,
      "FreeCastleDestroy": false,
      "InactivityKillEnabled": true,
      "InactivityKillTimeMin": 3600,
      "InactivityKillTimeMax": 604800,
      "InactivityKillSafeTimeAddition": 172800,
      "InactivityKillTimerMaxItemLevel": 84,
      "StartingProgressionLevel": 0,
      "DisableDisconnectedDeadEnabled": true,
      "DisableDisconnectedDeadTimer": 60,
      "DisconnectedSunImmunityTime": 300.0,
      "InventoryStacksModifier": 1.0,
      "DropTableModifier_General": 1.0,
      "DropTableModifier_Missions": 1.0,
      "MaterialYieldModifier_Global": 1.0,
      "BloodEssenceYieldModifier": 1.0,
      "JournalVBloodSourceUnitMaxDistance": 25.0,
      "PvPVampireRespawnModifier": 1.0,
      "CastleMinimumDistanceInFloors": 2,
      "ClanSize": 4,
      "BloodDrainModifier": 1.0,
      "DurabilityDrainModifier": 1.0,
      "GarlicAreaStrengthModifier": 1.0,
      "HolyAreaStrengthModifier": 1.0,
      "SilverStrengthModifier": 1.0,
      "SunDamageModifier": 1.0,
      "CastleDecayRateModifier": 1.0,
      "CastleBloodEssenceDrainModifier": 1.0,
      "CastleSiegeTimer": 420.0,
      "CastleUnderAttackTimer": 60.0,
      "CastleRaidTimer": 600.0,
      "CastleRaidProtectionTime": 1800.0,
      "CastleExposedFreeClaimTimer": 300.0,
      "CastleRelocationCooldown": 10800.0,
      "CastleRelocationEnabled": true,
      "AnnounceSiegeWeaponSpawn": true,
      "ShowSiegeWeaponMapIcon": false,
      "BuildCostModifier": 1.0,
      "RecipeCostModifier": 1.0,
      "CraftRateModifier": 1.0,
      "ResearchCostModifier": 1.0,
      "RefinementCostModifier": 1.0,
      "RefinementRateModifier": 1.0,
      "ResearchTimeModifier": 1.0,
      "DismantleResourceModifier": 1.0,
      "ServantConvertRateModifier": 1.0,
      "RepairCostModifier": 1.0,
      "Death_DurabilityFactorLoss": 0.125,
      "Death_DurabilityLossFactorAsResources": 1.0,
      "StarterEquipmentId": 28431735,
      "StarterResourcesId": 548330870,
      "VBloodUnitSettings": [
        {
          "UnitId": -1905691330,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 1124739990,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 2122229952,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -2025101517,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 763273073,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 1106149033,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 577478542,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -2039908510,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 1896428751,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -484556888,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1391546313,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 153390636,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1659822956,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1942352521,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -29797003,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -99012450,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 939467639,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1065970933,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 850622034,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 24378719,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 1688478381,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -680831417,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -548489519,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -203043163,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1968372384,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1208888966,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1007062401,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -2013903325,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 685266977,
          "DefaultUnlocked": true
        },
        {
          "UnitId": 114912615,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -1347412392,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -910296704,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -910296704,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -910296704,
          "DefaultUnlocked": true
        },
        {
          "UnitId": -910296704,
          "DefaultUnlocked": true
        }
      ],
      "UnlockedAchievements": [],
      "UnlockedResearchs": [],
      "GameTimeModifiers": {
        "DayDurationInSeconds": 1080.0,
        "DayStartHour": 9,
        "DayStartMinute": 0,
        "DayEndHour": 17,
        "DayEndMinute": 0,
        "BloodMoonFrequency_Min": 10,
        "BloodMoonFrequency_Max": 18,
        "BloodMoonBuff": 0.2
      },
      "VampireStatModifiers": {
        "MaxHealthModifier": 1.0,
        "PhysicalPowerModifier": 1.0,
        "SpellPowerModifier": 1.0,
        "ResourcePowerModifier": 1.0,
        "SiegePowerModifier": 1.0,
        "DamageReceivedModifier": 1.0,
        "ReviveCancelDelay": 5.0
      },
      "UnitStatModifiers_Global": {
        "MaxHealthModifier": 1.1,
        "PowerModifier": 1.1,
        "LevelIncrease": 0
      },
      "UnitStatModifiers_VBlood": {
        "MaxHealthModifier": 1.1,
        "PowerModifier": 1.1,
        "LevelIncrease": 0
      },
      "EquipmentStatModifiers_Global": {
        "MaxHealthModifier": 1.0,
        "ResourceYieldModifier": 5.0,
        "PhysicalPowerModifier": 1.0,
        "SpellPowerModifier": 1.0,
        "SiegePowerModifier": 1.0,
        "MovementSpeedModifier": 1.0
      },
      "CastleStatModifiers_Global": {
        "TickPeriod": 5.0,
        "SafetyBoxLimit": 1,
        "EyeStructuresLimit": 1,
        "TombLimit": 12,
        "VerminNestLimit": 4,
        "PrisonCellLimit": 16,
        "HeartLimits": {
          "Level1": {
            "FloorLimit": 50,
            "ServantLimit": 4,
            "HeightLimit": 3
          },
          "Level2": {
            "FloorLimit": 140,
            "ServantLimit": 5,
            "HeightLimit": 3
          },
          "Level3": {
            "FloorLimit": 240,
            "ServantLimit": 6,
            "HeightLimit": 3
          },
          "Level4": {
            "FloorLimit": 360,
            "ServantLimit": 7,
            "HeightLimit": 3
          },
          "Level5": {
            "FloorLimit": 550,
            "ServantLimit": 8,
            "HeightLimit": 3
          }
        },
        "CastleLimit": 2,
        "NetherGateLimit": 1,
        "ThroneOfDarknessLimit": 1
      },
      "PlayerInteractionSettings": {
        "TimeZone": "Local",
        "VSPlayerWeekdayTime": {
          "StartHour": 20,
          "StartMinute": 0,
          "EndHour": 22,
          "EndMinute": 0
        },
        "VSPlayerWeekendTime": {
          "StartHour": 20,
          "StartMinute": 0,
          "EndHour": 22,
          "EndMinute": 0
        },
        "VSCastleWeekdayTime": {
          "StartHour": 20,
          "StartMinute": 0,
          "EndHour": 22,
          "EndMinute": 0
        },
        "VSCastleWeekendTime": {
          "StartHour": 20,
          "StartMinute": 0,
          "EndHour": 22,
          "EndMinute": 0
        }
      },
      "TraderModifiers": {
        "StockModifier": 1.0,
        "PriceModifier": 1.0,
        "RestockTimerModifier": 1.0
      },
      "WarEventGameSettings": {
        "Interval": 1,
        "MajorDuration": 1,
        "MinorDuration": 1,
        "WeekdayTime": {
          "StartHour": 0,
          "StartMinute": 0,
          "EndHour": 23,
          "EndMinute": 59
        },
        "WeekendTime": {
          "StartHour": 0,
          "StartMinute": 0,
          "EndHour": 23,
          "EndMinute": 59
        },
        "ScalingPlayers1": {
          "PointsModifier": 1.0,
          "DropModifier": 1.0
        },
        "ScalingPlayers2": {
          "PointsModifier": 0.5,
          "DropModifier": 0.5
        },
        "ScalingPlayers3": {
          "PointsModifier": 0.25,
          "DropModifier": 0.25
        },
        "ScalingPlayers4": {
          "PointsModifier": 0.25,
          "DropModifier": 0.25
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-server-config
  labels:
    app: vrising
data:
  ServerHostSettings.json: |
    {
      "Name": "V Rising Server - ixxeL",
      "Description": "",
      "Port": 9876,
      "QueryPort": 9877,
      "MaxConnectedUsers": 40,
      "MaxConnectedAdmins": 4,
      "ServerFps": 30,
      "SaveName": "ixxel-new",
      "Password": "",
      "Secure": true,
      "ListOnSteam": false,
      "ListOnEOS": false,
      "AutoSaveCount": 20,
      "AutoSaveInterval": 120,
      "CompressSaveFiles": true,
      "GameSettingsPreset": "",
      "GameDifficultyPreset": "Difficulty_Normal",
      "AdminOnlyDebugEvents": true,
      "DisableDebugEvents": false,
      "API": {
        "Enabled": false
      },
      "Rcon": {
        "Enabled": false,
        "Port": 25575,
        "Password": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-config
  labels:
    app: vrising
data:
  TZ: 'Europe/Paris'
  SERVERNAME: 'VRising-Server-ixxeL'
---
apiVersion: v1
kind: Service
metadata:
  name: vrising-service
  labels:
    app: vrising
spec:
  type: LoadBalancer
  selector:
    app: vrising
  ports:
    - name: game
      protocol: UDP
      port: 9876
      targetPort: 9876
    - name: game2
      protocol: UDP
      port: 9877
      targetPort: 9877
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrising-deployment
  labels:
    app: vrising
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrising
  template:
    metadata:
      labels:
        app: vrising
    spec:
      containers:
        - name: vrising
          image: trueosiris/vrising
          imagePullPolicy: Always
          ports:
            - containerPort: 9876
              protocol: UDP
            - containerPort: 9877
              protocol: UDP
            - containerPort: 9878
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 27016
              protocol: UDP
          envFrom:
            - configMapRef:
                name: vrising-config # Contient d'autres configs comme TZ et SERVERNAME
          volumeMounts:
            - mountPath: /mnt/vrising/persistentdata/Settings/ServerHostSettings.json
              subPath: ServerHostSettings.json
              name: server-config-volume
            - mountPath: /mnt/vrising/persistentdata/Settings/ServerGameSettings.json
              subPath: ServerGameSettings.json
              name: server-game-volume
            - mountPath: /mnt/vrising/server
              name: server-volume
            - mountPath: /mnt/vrising/persistentdata
              name: persistentdata-volume
      restartPolicy: Always
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-pvc-new
        - name: persistentdata-volume
          persistentVolumeClaim:
            claimName: persistentdata-pvc-new
        - name: server-config-volume
          configMap:
            name: vrising-server-config
        - name: server-game-volume
          configMap:
            name: vrising-game-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc-new
  labels:
    app: vrising
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Taille demandée pour ce volume
  storageClassName: proxmox-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentdata-pvc-new
  labels:
    app: vrising
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi # Taille demandée pour ce volume
  storageClassName: proxmox-retain
