# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: vrising-server-config
#   labels:
#     app: vrising
# data:
#   ServerHostSettings.json: |
#     {
#       "Name": "ixxeL-vrising",
#       "Port": 27015,
#       "QueryPort": 27016,
#       "MaxConnectedUsers": 4,
#       "MaxConnectedAdmins": 4,
#       "ListOnSteam": true,
#       "ListOnEOS": true,
#       "SaveGameName": "",
#       "Password": "",
#       "Secure": true,
#       "AdministrationOnly": false,
#       "AutoSaveCount": 50,
#       "AutoSaveInterval": 600,
#       "GameSettingsPreset": "StandardPvP",
#       "CommandLineArguments": "",
#       "DisableInGameChat": false,
#       "EventEnabled": true
#     }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-config
  labels:
    app: vrising
data:
  TZ: 'Europe/Paris'
  SERVERNAME: 'trueosiris-V'
---
apiVersion: v1
kind: Service
metadata:
  name: vrising-service
  labels:
    app: vrising
spec:
  type: LoadBalancer
  selector:
    app: vrising
  ports:
    - name: game
      protocol: UDP
      port: 9876
      targetPort: 9876
    - name: game2
      protocol: UDP
      port: 9877
      targetPort: 9877
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrising-deployment
  labels:
    app: vrising
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrising
  template:
    metadata:
      labels:
        app: vrising
    spec:
      containers:
        - name: vrising
          image: trueosiris/vrising
          imagePullPolicy: Always
          ports:
            - containerPort: 9876
              protocol: UDP
            - containerPort: 9877
              protocol: UDP
            - containerPort: 9878
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 27016
              protocol: UDP
          envFrom:
            - configMapRef:
                name: vrising-config # Contient d'autres configs comme TZ et SERVERNAME
          volumeMounts:
            # - mountPath: /mnt/vrising/persistentdata/Settings/ServerHostSettings.json
            #   subPath: ServerHostSettings.json
              # name: server-config-volume
            - mountPath: /mnt/vrising/server
              name: server-volume
            - mountPath: /mnt/vrising/persistentdata
              name: persistentdata-volume
      restartPolicy: Always
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-pvc
        - name: persistentdata-volume
          persistentVolumeClaim:
            claimName: persistentdata-pvc
        # - name: server-config-volume
        #   configMap:
        #     name: vrising-server-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
  labels:
    app: vrising
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # Taille demandée pour ce volume
  storageClassName: proxmox-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentdata-pvc
  labels:
    app: vrising
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Taille demandée pour ce volume
  storageClassName: proxmox-retain
