---
operator:
  operator:
    image:
      repository: quay.io/minio/operator
      tag: v7.0.0
      pullPolicy: IfNotPresent
    replicaCount: 1

tenant:
  tenant:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-04-03T14-56-28Z
      pullPolicy: IfNotPresent

    # configuration:
    #   name: minio-creds
    # configSecret:
    #   accessKey: ''
    #   secretKey: ''
    #   existingSecret: true

    pools:
      ###
      # The number of MinIO Tenant Pods / Servers in this pool.
      # For standalone mode, supply 1. For distributed mode, supply 4 or more.
      # Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 1
        name: pool-0
        volumesPerServer: 1
        size: 10Gi
        storageClassName: nfs-csi-retain

    certificate:
      requestAutoCert: false

  ingress:
    api:
      enabled: true
      ingressClassName: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: minio-api.talos-genmachine.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
      tls:
        - hosts:
            - minio-api.talos-genmachine.fredcorp.com
          secretName: minio-api-tls-cert
      host: minio-api.talos-genmachine.fredcorp.com
      path: /
      pathType: Prefix
    console:
      enabled: true
      ingressClassName: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: minio.talos-genmachine.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
      tls:
        - hosts:
            - minio.talos-genmachine.fredcorp.com
          secretName: minio-tls-cert
      host: minio.talos-genmachine.fredcorp.com
      path: /
      pathType: Prefix
