---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard-data
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
  storageClassName: local-path-retain
  volumeName: pv-adguard-data