---
gha-runner-scale-set-controller:
  image:
    repository: 'ghcr.io/actions/gha-runner-scale-set-controller'
    pullPolicy: IfNotPresent
    tag: '0.10.1'

  serviceAccount:
    create: true
    name: 'arc-runner-controller'

  flags:
    logLevel: 'debug'
    logFormat: 'text'
    runnerMaxConcurrentReconciles: 2
    updateStrategy: 'immediate'
    excludeLabelPropagationPrefixes:
      - 'argocd.argoproj.io/instance'

gha-runner-scale-set:
  githubConfigUrl: 'https://github.com/ixxeL-DevOps'
  githubConfigSecret: gha-runner-secret
  maxRunners: 3
  minRunners: 0
  runnerGroup: 'fredcorp-talos'
  runnerScaleSetName: 'fredcorp'
  containerMode:
    type: 'kubernetes'
    kubernetesModeWorkVolumeClaim:
      accessModes: ['ReadWriteOnce']
      storageClassName: 'nfs-csi-delete'
      resources:
        requests:
          storage: 1Gi
  controllerServiceAccount:
    namespace: arc-system
    name: arc-runner-controller
  ## template is the PodSpec for each runner Pod
  template:
    spec:
      securityContext: # this section is related to error https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors#error-access-to-the-path-homerunner_work_tool-is-denied
        fsGroup: 123
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ['/home/runner/run.sh']
