---
gha-runner-scale-set-controller:
  image:
    repository: 'ghcr.io/actions/gha-runner-scale-set-controller'
    pullPolicy: IfNotPresent
    tag: '0.12.1'

  serviceAccount:
    create: true
    name: 'arc-runner-controller'

  flags:
    logLevel: 'debug'
    logFormat: 'text'
    runnerMaxConcurrentReconciles: 2
    updateStrategy: 'immediate'
    excludeLabelPropagationPrefixes:
      - 'argocd.argoproj.io/instance'

  metrics:
    controllerManagerAddr: ':8080'
    listenerAddr: ':8080'
    listenerEndpoint: '/metrics'

gha-runner-scale-set:
  githubConfigUrl: 'https://github.com/ixxeL-DevOps'
  githubConfigSecret: gha-runner-secret
  maxRunners: 3
  minRunners: 1
  runnerGroup: 'fredcorp-talos'
  runnerScaleSetName: 'fredcorp'
  containerMode:
    type: 'kubernetes'
    kubernetesModeWorkVolumeClaim:
      accessModes: ['ReadWriteOnce']
      storageClassName: 'nfs-csi-delete'
      resources:
        requests:
          storage: 1Gi
  controllerServiceAccount:
    namespace: arc-system
    name: arc-runner-controller
  ## template is the PodSpec for each runner Pod
  template:
    spec:
      securityContext: # this section is related to error https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors#error-access-to-the-path-homerunner_work_tool-is-denied
        fsGroup: 123
      containers:
        - name: runner
          # renovate: datasource=docker depName=ghcr.io/actions/actions-runner
          image: ghcr.io/actions/actions-runner:2.327.1
          command: ['/home/runner/run.sh']
          env:
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER # disable container job checking : https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#configuring-kubernetes-mode
              value: 'false'

  listenerMetrics:
    counters:
      gha_started_jobs_total:
        labels: ['repository', 'organization', 'enterprise', 'job_name', 'event_name']
      gha_completed_jobs_total:
        labels: ['repository', 'organization', 'enterprise', 'job_name', 'event_name', 'job_result']
    gauges:
      gha_assigned_jobs:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_running_jobs:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_registered_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_busy_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_min_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_max_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_desired_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
      gha_idle_runners:
        labels: ['name', 'namespace', 'repository', 'organization', 'enterprise']
