---
gatus:
  image:
    repository: twinproduction/gatus
    tag: 'v5.16.0@sha256:bb738c87cf2e2a08b8fff180cfc433e7b8b87bb1779c1fb1b00f8b748673e3c3'
    sha: ''
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: {}
    pathType: Prefix
    hosts:
      - gatus.k0s-fullstack.fredcorp.com
