---
loki:
  loki:
    image:
      registry: docker.io
      repository: grafana/loki
      tag: 3.5.4

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: loki.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    ingressClassName: traefik
    hosts:
      - loki.talos-genmachine.fredcorp.com
    tls:
      - hosts:
          - loki.talos-genmachine.fredcorp.com
        secretName: loki-tls-cert

alloy:
  image:
    registry: 'docker.io'
    repository: grafana/alloy
    tag: v1.10.2

  alloy:
    configMap:
      create: true
      content: |
        loki.write "default" {
          endpoint {
            url = "http://loki.loki:3100/loki/api/v1/push"
          }
        }

        discovery.kubernetes "pod" {
          role = "pod"
        }

        discovery.relabel "pod_logs" {
          targets = discovery.kubernetes.pod.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            action = "replace"
            target_label = "namespace"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            action = "replace"
            target_label = "pod"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "container"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
            action = "replace"
            target_label = "app"
          }

          rule {
            source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "job"
            separator = "/"
            replacement = "$1"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
            action = "replace"
            target_label = "__path__"
            separator = "/"
            replacement = "/var/log/pods/*$1/*.log"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_container_id"]
            action = "replace"
            target_label = "container_runtime"
            regex = "^(\\S+):\\/\\/.+$"
            replacement = "$1"
          }
        }

        loki.source.kubernetes "pod_logs" {
          targets    = discovery.relabel.pod_logs.output
          forward_to = [loki.process.pod_logs.receiver]
        }

        loki.process "pod_logs" {
          stage.static_labels {
              values = {
                cluster = "genmachine",
              }
          }

          forward_to = [loki.write.default.receiver]
        }

      name: null
      key: null

    clustering:
      enabled: false

  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: alloy.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    path: /
    faroPort: 12345
    pathType: Prefix
    hosts:
      - alloy.talos-genmachine.fredcorp.com
    tls:
      - secretName: alloy-tls-cert
        hosts:
          - alloy.talos-genmachine.fredcorp.com
