---
vault:
  global:
    enabled: true

  injector:
    enabled: true

  server:
    enabled: true
    image:
      repository: 'hashicorp/vault'
      tag: '1.18.5@sha256:750bb37c1638fa194ab37053a81618c61bb0491ddec6fccac87c07a8e6cd8166'
      pullPolicy: IfNotPresent

    updateStrategyType: 'RollingUpdate'

    statefulSet:
      annotations:
        argocd.argoproj.io/sync-wave: '1'

    dataStorage:
      enabled: true
      size: 10Gi
      mountPath: /vault/data
      storageClass: local-path-retain
      accessMode: ReadWriteOnce

    affinity: '' # set empty to allow single node scheduling

    # persistentVolumeClaimRetentionPolicy:
    #   whenDeleted: Retain
    #   whenScaled: Retain

    ingress:
      enabled: true
      labels: {}
      annotations: {}
      ingressClassName: traefik
      pathType: Prefix
      activeService: true
      hosts:
        - host: vault.k0s-fullstack.fredcorp.com
          paths: []
      tls:
        - hosts:
            - vault.k0s-fullstack.fredcorp.com

  standalone:
    enabled: true
    config: |-
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  ui:
    enabled: true
    publishNotReadyAddresses: true
    activeVaultPodOnly: false
    serviceType: ClusterIP
    serviceNodePort:
    externalPort: 8200
    targetPort: 8200
