---
csi-driver-nfs:
  controller:
    logLevel: 4
  node:
    logLevel: 4
  image:
    baseRepo: registry.k8s.io
    nfs:
      repository: registry.k8s.io/sig-storage/nfsplugin
      tag: v4.10.0
      pullPolicy: IfNotPresent
    csiProvisioner:
      repository: registry.k8s.io/sig-storage/csi-provisioner
      tag: v5.2.0
      pullPolicy: IfNotPresent
    csiResizer:
      repository: registry.k8s.io/sig-storage/csi-resizer
      tag: v1.13.1
      pullPolicy: IfNotPresent
    csiSnapshotter:
      repository: registry.k8s.io/sig-storage/csi-snapshotter
      tag: v8.2.0
      pullPolicy: IfNotPresent
    livenessProbe:
      repository: registry.k8s.io/sig-storage/livenessprobe
      tag: v2.15.0
      pullPolicy: IfNotPresent
    nodeDriverRegistrar:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.13.0
      pullPolicy: IfNotPresent
    externalSnapshotter:
      repository: registry.k8s.io/sig-storage/snapshot-controller
      tag: v8.2.0
      pullPolicy: IfNotPresent
