---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.0
  parallelism: 1
  policy:
    rebootMode: default
    timeout: 30m
    force: false
  drain:
    ignoreDaemonSets: true
    force: true
    deleteLocalData: false
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: "status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')"
      timeout: 10m
