---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
  namespace: system-upgrade
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.11.6
  parallelism: 1
  policy:
    debug: true          # Optional, verbose logging
    force: false         # Optional, skip etcd health checks
    rebootMode: default  # Optional, default|powercycle
    placement: soft      # Optional, hard|soft
    stage: false         # Optional, stage upgrade
    timeout: 30m         # Optional, per-node upgrade timeout
  drain:
    ignoreDaemonSets: true
    force: true
    deleteLocalData: false
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: "status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')"
      timeout: 10m
  talosctl:
    image:
      # renovate: datasource=docker depName=ghcr.io/siderolabs/talosctl
      tag: v1.11.0                             # Optional, auto-detected
      pullPolicy: IfNotPresent                 # Optional, default
