---
adguard-home:
  image:
    repository: adguard/adguardhome
    pullPolicy: Always
    tag: v0.107.57@sha256:5c536c1e25f76693ae7ee5e64e8a029893e0f3f1778c8d2a9581383e60cfa9b9

  services:
    adminPanel:
      type: ClusterIP
      port: 3000
    http:
      type: ClusterIP
      port: 80
    https:
      enabled: true
      type: ClusterIP
      port: 443
    dns:
      enabled: true
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: 192.168.1.195-ip
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.1.195
      tcp:
        port: 53
        nodePort:
      udp:
        port: 53
        nodePort:
    dnsOverTls:
      enabled: false
    #   type: LoadBalancer
    #   annotations:
    #     metallb.universe.tf/allow-shared-ip: 192.168.1.195-ip
    #   # externalTrafficPolicy: Local
    #   loadBalancerIP: 192.168.1.195
    #   port: 853
    dnsOverQuic:
      enabled: false
    #   type: LoadBalancer
    #   annotations:
    #     metallb.universe.tf/allow-shared-ip: 192.168.1.195-ip
    #   # externalTrafficPolicy: Local
    #   loadBalancerIP: 192.168.1.195
    #   port1:
    #     port: 784
    #     nodePort:
    #   port2:
    #     port: 8853
    #     nodePort:
    dnscrypt:
      enabled: false
      #   type: LoadBalancer
      #   annotations:
      #     metallb.universe.tf/allow-shared-ip: 192.168.1.195-ip
      #   # externalTrafficPolicy: Local
      #   loadBalancerIP: 192.168.1.195
      #   tcp:
      #     port: 5443
      #     nodePort:
      #   udp:
      #     port: 5443
      #     nodePort:

  ingresses:
    adminPanel:
      enabled: false
      className: traefik
      hosts:
        - host: adguard-admin.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: adguard-admin-tls
      #    hosts:
      #      - adguard-admin.k0s-fullstack.fredcorp.com
    http:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: adguard.k0s-fullstack.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
      hosts:
        - host: adguard.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: adguard-tls-cert
          hosts:
            - adguard.k0s-fullstack.fredcorp.com
    https:
      enabled: false
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: adguard.k0s-fullstack.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
        traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
      hosts:
        - host: adguard.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: adguard-tls-cert
          hosts:
            - adguard.k0s-fullstack.fredcorp.com

  persistence:
    existingClaim: pvc-adguard-data
    volumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  bootstrapEnabled: false
