---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-adguard-data
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/lib/rancher/k3s/storage/adguard-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3d-home-server-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard-data
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: local-path
  volumeName: pv-adguard-data
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: adguard
  namespace: kube-system
spec:
  targetNamespace: adguard
  createNamespace: true
  version: 0.19.0
  chart: adguard-home
  repo: https://helm-charts.rm3l.org
  valuesContent: |-
    image:
      repository: adguard/adguardhome
      pullPolicy: Always
      tag: "v0.107.56"

    services:
      adminPanel:
        type: ClusterIP
        port: 3000
      http:
        type: ClusterIP
        port: 80
      https:
        enabled: true
        type: ClusterIP
        port: 443
      dns:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        tcp:
          port: 53
          nodePort:
        udp:
          port: 53
          nodePort:
      dnsOverTls:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        port: 853
      dnsOverQuic:
        enabled: true
        type: LoadBalancer
        port1:
          port: 784
          nodePort:
        port2:
          port: 8853
          nodePort:
        externalTrafficPolicy: Local
      dnscrypt:
        enabled: false
        type: LoadBalancer
        externalTrafficPolicy: Local
        tcp:
          port: 5443
          nodePort:
        udp:
          port: 5443
          nodePort:

    ingresses:
      adminPanel:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard-admin.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: adguard-admin-tls
        #    hosts:
        #      - adguard-admin.fullstack.fredcorp.com
      http:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - adguard.fullstack.fredcorp.com
      https:
        enabled: true
        className: "traefik"
        hosts:
          - host: adguard-secure.fullstack.fredcorp.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: []
        #  - secretName: adguard-secure-tls
        #    hosts:
        #      - adguard-secure.fullstack.fredcorp.com

    persistence:
      existingClaim: pvc-adguard-data
      volumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

    bootstrapEnabled: false



