# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: admin
# spec:
#   provider:
#     vault:
#       server: "https://vault.fredcorp.com"
#       path: "admin"
#       version: "v2"
#       caProvider:
#         type: "ConfigMap"
#         namespace: "external-secrets"
#         name: "fredcorp-pki-certs"
#         key: "vault-pki-certs.pem"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "external-secrets"
#           serviceAccountRef:
#             name: "eso-auth"
#             namespace: external-secrets
#           secretRef:
#             name: "eso-auth"
#             key: "token"
#             namespace: external-secrets
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  targetNamespace: external-secrets
  createNamespace: true
  version: 0.14.2
  chart: external-secrets
  repo: https://charts.external-secrets.io
  valuesContent: |-
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
      conversion:
        enabled: true
