---
kube-prometheus-stack:
  prometheus-node-exporter:
    prometheus:
      monitor:
        relabelings:
          - action: replace
            sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: nodename
  prometheus:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: true
  coreDns:
    enabled: true
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      k8sContainerCpuUsageSecondsTotal: true
      k8sContainerMemoryCache: true
      k8sContainerMemoryRss: true
      k8sContainerMemorySwap: true
      k8sContainerResource: true
      k8sContainerMemoryWorkingSetBytes: true
      k8sPodOwner: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubeControllerManager: true
      kubelet: true
      kubeProxy: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeSchedulerAlerting: true
      kubeSchedulerRecording: true
      kubeStateMetrics: true
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true
      windows: true
  grafana:
    enabled: true
    adminPassword: password
    defaultDashboardsEnabled: false
    defaultDashboardsEditable: true
    defaultDashboardsTimezone: Europe/Paris
    persistence:
      enabled: false
      accessModes:
        - ReadWriteMany
      finalizers:
        - kubernetes.io/pvc-protection
      size: 10Gi
      type: pvc
    plugins:
      - grafana-piechart-panel
      - grafana-polystat-panel
      - grafana-clock-panel
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'grafana-dashboards-kubernetes'
            orgId: 1
            folder: 'k8s'
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
          - name: 'grafana-dashboards-argocd'
            orgId: 1
            folder: 'argocd'
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-argocd
    dashboards:
      grafana-dashboards-argocd:
        operational:
          url: https://raw.githubusercontent.com/adinhodovic/argo-cd-mixin/main/dashboards_out/argo-cd-operational-overview.json
          token: ''
        application:
          url: https://raw.githubusercontent.com/adinhodovic/argo-cd-mixin/main/dashboards_out/argo-cd-application-overview.json
          token: ''
        notification:
          url: https://raw.githubusercontent.com/adinhodovic/argo-cd-mixin/main/dashboards_out/argo-cd-notifications-overview.json
          token: ''
      grafana-dashboards-kubernetes:
        k8s-system-api-server:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
          token: ''
        k8s-system-coredns:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
          token: ''
        k8s-views-global:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
          token: ''
        k8s-views-namespaces:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
          token: ''
        k8s-views-nodes:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
          token: ''
        k8s-views-pods:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
          token: ''
        popeye:
          url: 'https://raw.githubusercontent.com/derailed/popeye/refs/heads/master/grafana/popeye-dashboard.json'
          token: ''

    sidecar:
      dashboards:
        SCProvider: true
        defaultFolderName: null
        enabled: true
        folder: /tmp/dashboards
        folderAnnotation: grafana_folder
        label: grafana_dashboard
        labelValue: 1
        provider:
          allowUiUpdates: true
          disableDelete: false
          folder: ''
          foldersFromFilesStructure: true
          name: sidecarProvider
          orgid: 1
          type: file
        resource: both
        searchNamespace: ALL
      enableUniqueFilenames: false

prometheus-blackbox-exporter:
  extraVolumes:
    - name: fredcorp-ca-chain
      secret:
        defaultMode: 420
        secretName: fredcorp-ca-chain # Using cert-manager Bundle for chain CA fredcorp (Vault PKI)
  extraVolumeMounts:
    - name: fredcorp-ca-chain
      mountPath: /etc/ssl/certs/fredcorp-ca-chain.pem
      subPath: fredcorp-ca-chain.pem
      readOnly: true
  serviceMonitor:
    enabled: true
    # Default values that will be used for all ServiceMonitors created by `targets`
    defaults:
      additionalMetricsRelabels: {}
      additionalRelabeling: []
      labels:
        release: prometheus

    targets:
      - name: traefik # Human readable URL that will appear in Prometheus / AlertManager
        url: https://traefik.k0s-fullstack.fredcorp.com # The URL that blackbox will scrape
        hostname: traefik.k0s-fullstack.fredcorp.com # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
        labels: {} # Map of labels for ServiceMonitor. Overrides value set in `defaults`
        interval: 60s # Scraping interval. Overrides value set in `defaults`
        scrapeTimeout: 60s # Scrape timeout. Overrides value set in `defaults`
        module: http_2xx # Module used for scraping. Overrides value set in `defaults`
        additionalMetricsRelabels: {} # Map of metric labels and values to add
        additionalRelabeling: [] # List of metric relabeling actions to run
      - name: adguard # Human readable URL that will appear in Prometheus / AlertManager
        url: https://adguard.k0s-fullstack.fredcorp.com
        hostname: adguard.k0s-fullstack.fredcorp.com
        labels: {}
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
        additionalMetricsRelabels: {}
        additionalRelabeling: []
