---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-argocd-token
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-argocd-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homepage/argocd/genmachine
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-authentik-token
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-authentik-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homepage/authentik/genmachine
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-adguard-creds
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-adguard-creds
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: adguard/creds
        property: password
    - secretKey: user
      remoteRef:
        key: adguard/creds
        property: user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-grafana-password
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-grafana-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: grafana/credentials/genmachine
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-proxmox-creds
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-proxmox-creds
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: proxmox/creds/genmachine
        property: token
    - secretKey: user
      remoteRef:
        key: proxmox/creds/genmachine
        property: user
