---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-argocd-token
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: homepage-argocd-token
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_ARGOCD_TOKEN
      remoteRef:
        key: homepage/argocd/genmachine
        property: token
