cilium:
  securityContext:
    privileged: true
  priorityClassName: 'system-node-critical'
  debug:
    enabled: false
  gatewayAPI:
    enabled: false
  ipam:
    mode: kubernetes
  kubeProxyReplacement: true
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  k8sServiceHost: localhost
  k8sServicePort: 7445
  ingressController:
    enabled: false

  envoy:
    priorityClassName: 'system-node-critical'
  operator:
    priorityClassName: 'system-node-critical'
