---
cilium:
  securityContext:
    privileged: true # Useful for Talos linux
    capabilities:
      ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
      cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]

  priorityClassName: 'system-node-critical'
  debug:
    enabled: false
  gatewayAPI:
    enabled: false
  ipam:
    mode: kubernetes
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 7445
  kubeProxyReplacement: true
  ingressController:
    enabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  envoy:
    priorityClassName: 'system-node-critical'
  operator:
    rollOutPods: true
    replicas: 2
    priorityClassName: 'system-node-critical'
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                io.cilium/app: operator

  enableLBIPAM: true
  l2announcements:
    enabled: true
  devices: eth+

  rollOutCiliumPods: true

  localRedirectPolicy: true
