---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: burrito
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../common
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/burrito/*'
            exclude: false
          - path: 'gitops/manifests/burrito/common'
            exclude: true
          - path: 'gitops/manifests/burrito/beelink'
            exclude: true
  template:
    metadata:
      name: 'burrito-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../common
    spec:
      project: infra-core
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: burrito
      sources:
        - path: 'gitops/manifests/burrito/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: burrito
            valueFiles:
              - $values/gitops/manifests/burrito/common/common-values.yaml
              - $values/gitops/manifests/burrito/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 6
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
