---
version: "3"
tasks:
  k3d:deploy:
    desc: "Create k3d cluster"
    cmds:
    - |
      envsubst < {{.PWD}}/k3d-template.yaml > k3d.yaml
      k3d cluster create --config {{.PWD}}/k3d.yaml
    vars:
      PWD:
        sh: pwd

  k3d:destroy:
    desc: "Destroy k3d cluster"
    cmds:
    - |
      k3d cluster delete --config {{.PWD}}/k3d.yaml
    vars:
      PWD:
        sh: pwd
