---
version: "3"
tasks:
  k3d:deploy:
    desc: "Create k3d cluster"
    cmds:
    - |
      envsubst < {{.PWD}}/k3d-template.yaml > k3d.yaml
      k3d cluster create --config {{.PWD}}/k3d.yaml
    vars:
      PWD:
        sh: pwd

  k3d:destroy:
    desc: "Destroy k3d cluster"
    cmds:
    - |
      k3d cluster delete --config {{.PWD}}/k3d.yaml
    vars:
      PWD:
        sh: pwd

  nc:wireguard:
    desc: "Test wireguard UDP port"
    cmds:
    - |
      nc -zv -u 127.0.0.1 51820

  nc:dns:
    desc: "Test DNS UDP port"
    cmds:
    - |
      nc -zv -u 127.0.0.1 53