---
metallb:
  controller:
    image:
      repository: quay.io/metallb/controller
      tag: v0.15.2
      pullPolicy: IfNotPresent
  speaker:
    image:
      repository: quay.io/metallb/speaker
      tag: v0.15.2
      pullPolicy: IfNotPresent
