---
wg-portal:
  # image:
  #   repository: ghcr.io/h44z/wg-portal
  #   pullPolicy: IfNotPresent
  #   tag: '1.0.19'
  podSecurityContext:
    sysctls:
      - name: net.ipv4.ip_forward
        value: '1'
      - name: net.ipv4.conf.all.src_valid_mark
        value: '1'
  securityContext:
    privileged: true
    capabilities:
      add:
        - NET_ADMIN
        - SYS_MODULE

    # capabilities:
    #   # -- Add capabilities to the container
    #   add:
    #     - NET_ADMIN

  service:
    mixed:
      enabled: false
      type: LoadBalancer
    web:
      type: ClusterIP
      port: 8888
      appProtocol: http
    wireguard:
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
        - 51820
    metrics:
      port: 8787

  config:
    # auth: {}
    # core:
    #   admin_user: admin
    #   admin_password: password
    web:
      external_url: https://wireguard.k0s-fullstack.fredcorp.com
    advanced:
      log_level: debug

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
    tls: false
