---
wg-portal:
  service:
    mixed:
      enabled: false
      type: LoadBalancer
    web:
      type: ClusterIP
      port: 8888
      appProtocol: http
    wireguard:
      type: LoadBalancer
      ports:
        - 51820
    metrics:
      port: 8787

  config:
    auth: {}
    core:
      admin_user: admin
      admin_password: password
    web:
      external_url: http://wireguard.k0s-fullstack.fredcorp.com
    advanced:
      log_level: debug

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
    tls: false
