---
wg-portal:
  image:
    repository: wgportal/wg-portal
  #   pullPolicy: IfNotPresent
  #   tag: '1.0.19'
  podSecurityContext:
    sysctls:
      - name: net.ipv4.ip_forward
        value: '1'
      - name: net.ipv4.conf.all.src_valid_mark
        value: '1'
  securityContext:
    # privileged: true
    capabilities:
      add:
        - NET_ADMIN
        # - SYS_MODULE

  persistence:
    enabled: true
    storageClass: 'local-path-retain'
    accessMode: ReadWriteOnce
    size: 1Gi

  service:
    mixed:
      enabled: false
      type: LoadBalancer
    web:
      type: ClusterIP
      port: 8888
      appProtocol: http
    wireguard:
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
        - 51820
    metrics:
      port: 8787

  # initContainers:
  #   - name: update-ca
  #     image: alpine:3.19
  #     command:
  #       - /bin/sh
  #       - -c
  #       - |
  #         apk add ca-certificates
  #         cp /usr/local/share/ca-certificates/root-ca.crt /etc/ssl/certs/root-ca.crt
  #         update-ca-certificates
  #     volumeMounts:
  #       - name: trusted-certs
  #         mountPath: /usr/local/share/ca-certificates/root-ca.crt
  #         subPath: root-ca.crt

  volumes:
    - name: trusted-certs
      secret:
        defaultMode: 420
        secretName: wireguard-trusted-certs

  volumeMounts:
    - name: trusted-certs
      mountPath: /etc/ssl/certs/root-ca.crt
      subPath: root-ca.crt
      readOnly: true

  config:
    auth:
      callback_url_prefix: https://wireguard.k0s-fullstack.fredcorp.com/api/v0
      oidc:
        - id: Authentik
          provider_name: Authentik
          display_name: Login with Authentik
          base_url: https://authentik.k0s-fullstack.fredcorp.com/application/o/fullstack-wireguard/
          client_id: rsWRDGLVwpm0Ey5dVd7b3PMdOZJGabAqE2pUUnBn
          client_secret: Wd2tec2z9Jf6gmzRicCPae46rmp0L7xME8soddrz0Dss9Yp2QKWg63VYON8plbEUjmT6jLma2igGbKXHrzhNVSfWACZ78A2F7JWm2PDUWlPnmDm9XSOfKuRVIHnznx3B
          extra_scopes:
            - profile
            - email
            - openid
            - is_admin
          field_map:
            email: email
            user_identifier: email
            is_admin: is_admin
          registration_enabled: true

    # auth: {}
    # core:
    #   admin_user: admin
    #   admin_password: password
    web:
      external_url: https://wireguard.k0s-fullstack.fredcorp.com
    advanced:
      log_level: debug

  ingress:
    enabled: true
    className: traefik
    # annotations:
    #   traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
    tls: true
