---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/prometheus/*'
            exclude: false
          - path: 'gitops/manifests/prometheus/values'
            exclude: true
          - path: 'gitops/manifests/prometheus/beelink'
            exclude: true
          - path: 'gitops/manifests/prometheus/k0s'
            exclude: true
          - path: 'gitops/manifests/prometheus/dashboards'
            exclude: true
  template:
    metadata:
      name: 'prometheus-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values
    spec:
      project: infra-monitoring
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: prometheus
      sources:
        - path: 'gitops/manifests/prometheus/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: prometheus
            valueFiles:
              - $values/gitops/manifests/prometheus/values/common-values.yaml
              - $values/gitops/manifests/prometheus/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
        - path: 'gitops/manifests/prometheus/dashboards/system'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
        - path: 'gitops/manifests/prometheus/dashboards/storage'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
        - path: 'gitops/manifests/prometheus/dashboards/logs'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 6
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        managedNamespaceMetadata:
          labels:
            bundle.chain/inject: 'enabled'
