---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CP_VMS: 1-DE:CA:FF:10:12:10-192.168.1.151 2-DE:CA:FF:10:12:11-192.168.1.152 3-DE:CA:FF:10:12:12-192.168.1.153
  ALL_VMS: '{{.CP_VMS}}'
  VMID_PREFIX: 20

tasks:
  reset-px-talos:
    desc: Reset px-talos cluster
    cmds:
      - task: destroy-px-talos
      - task: create-px-talos
      - task: wait-for-startup

  start-px-talos:
    desc: Start px-talos cluster
    cmds:
      - for: { var: ALL_VMS, split: ' ' }
        task: start-vm-{{.ITEM}}

  stop-px-talos:
    desc: Stop px-talos cluster
    cmds:
      - for: { var: ALL_VMS, split: ' ' }
        task: stop-vm-{{.ITEM}}

  unmount-px-talos-cdrom:
    desc: Unmount px-talos cluster CD-ROM drives
    cmds:
      - for: { var: ALL_VMS, split: ' ' }
        task: unmount-cdrom-{{.ITEM}}

  destroy-px-talos:
    desc: Destroy px-talos cluster
    cmds:
      - for: { var: ALL_VMS, split: ' ' }
        task: destroy-vm-{{.ITEM}}

  create-px-talos:
    desc: Create px-talos cluster
    cmds:
      - for: { var: CP_VMS, split: ' ' }
        task: create-cp-vm-{{.ITEM}}

  wait-for-startup:
    internal: true
    cmds:
      - for: { var: ALL_VMS, split: ' ' }
        task: wait-for-startup-{{.ITEM}}

  start-vm-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
    cmds:
      - cmd: ssh proxmox-genmachine -- qm start {{.VMID_PREFIX}}{{.vmid}}
        ignore_error: true

  stop-vm-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
    cmds:
      - cmd: ssh proxmox-genmachine -- qm stop {{.VMID_PREFIX}}{{.vmid}}
        ignore_error: true

  unmount-cdrom-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
    cmds:
      - cmd: ssh proxmox-genmachine -- qm set {{.VMID_PREFIX}}{{.vmid}} -ide0 media=cdrom,file=none

  destroy-vm-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
    cmds:
      - cmd: ssh proxmox-genmachine -- qm stop {{.VMID_PREFIX}}{{.vmid}}
        ignore_error: true
      - cmd: ssh proxmox-genmachine -- qm destroy {{.VMID_PREFIX}}{{.vmid}}
        ignore_error: true

  create-cp-vm-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
      mac: '{{index .MATCH 1}}'
      ip: '{{index .MATCH 2}}'
    cmds:
      - cmd: |
          ssh proxmox-genmachine -- qm create {{.VMID_PREFIX}}{{.vmid}} \
            --name talos-{{.vmid}} \
            --description stage-{{.vmid}} \
            --ide0 QNAP:iso/metal-amd64.iso,media=cdrom \
            --boot 'order=ide0\;scsi0' \
            --memory 8192 \
            --sockets 1 \
            --cores 4 \
            --cpu host \
            --scsihw 'virtio-scsi-pci' \
            --vga type=virtio,memory=32 \
            --scsi0 local-lvm:100,backup=0 \
            --net0 model=virtio,bridge=vmbr0,macaddr={{.mac}},mtu=1500 \
            --start 1

  wait-for-startup-*-*-*:
    internal: true
    vars:
      vmid: '{{index .MATCH 0}}'
      mac: '{{index .MATCH 1}}'
      ip: '{{index .MATCH 2}}'
    cmd: ping -o -q {{.ip}}
