---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gha-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: gha-runner-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_app_id
      remoteRef:
        key: github/gh-app/ixxel-devops/pipelines
        property: APP_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: github_app_installation_id
      remoteRef:
        key: github/gh-app/ixxel-devops/pipelines
        property: INSTALL_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: github_app_private_key
      remoteRef:
        key: github/gh-app/ixxel-devops/pipelines
        property: PRIVATE_KEY
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
