---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homarr-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  local:
    path: /home/fred/git/github/ixxeL-GitOps/fullstack/k0s-home/local-storage/homarr-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fullstack