---
gha-runner-scale-set-controller:
  image:
    repository: 'ghcr.io/actions/gha-runner-scale-set-controller'
    pullPolicy: IfNotPresent
    tag: '0.10.1'

  flags:
    logLevel: 'debug'
    logFormat: 'text'
    runnerMaxConcurrentReconciles: 2
    updateStrategy: 'immediate'
    excludeLabelPropagationPrefixes:
      - 'argocd.argoproj.io/instance'
