---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: admin
spec:
  provider:
    vault:
      server: https://vault.talos-genmachine.fredcorp.com
      path: admin
      version: v2
      caProvider: # Using cert-manager Bundle for chain CA fredcorp (Vault PKI)
        type: Secret
        namespace: external-secrets
        name: fredcorp-ca-chain
        key: fredcorp-ca-chain.pem
      auth:
        kubernetes:
          mountPath: genmachine
          role: eso
          serviceAccountRef:
            name: eso-auth
            namespace: external-secrets
          secretRef:
            name: eso-auth
            key: token
            namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tokenreview-binding-externalsecrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: eso-auth
    namespace: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-auth
  namespace: external-secrets
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: eso-auth
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: eso-auth
