---
strimzi-kafka-operator:
  defaultImageRegistry: quay.io
  defaultImageRepository: strimzi
  defaultImageTag: 0.46.0

  image:
    registry: ""
    repository: ""
    name: operator
    tag: ""

kafka-ui:
  image:
    registry: ghcr.io
    repository: kafbat/kafka-ui
    pullPolicy: IfNotPresent
    tag: "v1.2.0"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: kafka-ui.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    ingressClassName: "traefik"
    host: "kafka-ui.talos-genmachine.fredcorp.com"
    tls:
      enabled: true
      secretName: "kafka-ui-tls-cert"
