---
traefik:
  image:
    registry: docker.io
    repository: traefik
    tag: v3.7.1
    pullPolicy: IfNotPresent

  globalArguments:
    - --global.checknewversion=false
    - --global.sendanonymoususage=false

  tlsStore:
    default:
      defaultCertificate:
        secretName: k0s-fullstack-wildcard

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  service:
    loadBalancerIP: '192.168.1.191'
