---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-trusted-certs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: wireguard-trusted-certs
    creationPolicy: Owner
  data:
    - secretKey: root-ca.crt
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: wildcard/root-ca
        property: cert
