---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-k0s-wg-portal
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-retain
  volumeName: pv-wireguard-data
