---
crossplane:
  image:
    repository: xpkg.upbound.io/crossplane/crossplane
    tag: 'v2.2.1'
    pullPolicy: IfNotPresent

komoplane:
  image:
    repository: komodorio/komoplane
    pullPolicy: IfNotPresent
    tag: '0.2.1'

  ingress:
    enabled: true
    className: 'traefik'
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: komoplane.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    hosts:
      - host: komoplane.talos-genmachine.fredcorp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: komoplane-tls-cert
        hosts:
          - komoplane.talos-genmachine.fredcorp.com

crossview:
  image:
    repository: ghcr.io/crossplane-contrib/crossview
    pullPolicy: IfNotPresent
    tag: 'v4.3.0'

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: crossview.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: crossview.talos-genmachine.fredcorp.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: crossview-tls-cert
        hosts:
          - crossview.talos-genmachine.fredcorp.com

  database:
    persistence:
      storageClass: proxmox-delete
      size: 5Gi

  secrets:
    adminUsername:
      secretKeyRef:
        name: crossview-credentials
        key: admin-username
    adminPassword:
      secretKeyRef:
        name: crossview-credentials
        key: admin-password
    dbPassword:
      secretKeyRef:
        name: crossview-credentials
        key: db-password
    sessionSecret:
      secretKeyRef:
        name: crossview-credentials
        key: session-secret
