{{- /*
If the operator configures the service input variable, then also create a Service resource that exposes the Pod as a
stable endpoint that can be routed within the Kubernetes cluster.
*/ -}}
{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homarr.fullname" . }}
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
      {{- end }}
    {{- if .Values.service.clusterIP }}
    clusterIP: {{ .Values.service.clusterIP }}
    {{- end }}
  selector:
    {{- include "homarr.selectorLabels" . | nindent 4 }}
  {{- end }}
