# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: InvitationFlow
entries:
  - model: authentik_stages_invitation.invitationstage
    attrs:
      name: invite
    identifiers:
      name: invite
  - model: authentik_flows.flowstagebinding
    attrs:
      slug: invite
      invalid_response_action: retry
      order: 0
      policy_engine_mode: any
      re_evaluate_policies: true
      stage: !Find [authentik_stages_invitation.invitationstage, [name, invite]]
      target: !Find [authentik_flows.flow, [slug, default-enrollment-flow]]
    identifiers:
      target: !Find [authentik_flows.flow, [slug, default-enrollment-flow]]
