---
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - ./groups.yaml
      - ./service-accounts.yaml
      - ./properties.yaml
      - ./oidc-argocd.yaml
      - ./oidc-vault.yaml
      - ./oidc-homarr.yaml
      - ./oidc-wireguard.yaml
      - ./proxy-traefik.yaml
      - ./proxy-homepage.yaml
      - ./proxy-adguard.yaml
      - ./flows.yaml
      - ./enrollment.yaml
