# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: ServiceAccounts
entries:
  - model: authentik_core.user
    identifiers:
      name: sa-homarr
    attrs:
      attributes:
        goauthentik.io/user/token-expires: true
      groups:
        - !Find [authentik_core.group, [name, 'Argocd admins']]
        - !Find [authentik_core.group, [name, 'Adguard admins']]
        - !Find [authentik_core.group, [name, sa-homarr]]
      is_active: true
      name: sa-homarr
      path: goauthentik.io/service-accounts
      type: service_account
      username: sa-homarr
  - model: authentik_core.user
    identifiers:
      name: sa-homepage
    attrs:
      attributes:
        goauthentik.io/user/token-expires: true
      groups:
        - !Find [authentik_core.group, [name, 'Argocd admins']]
        - !Find [authentik_core.group, [name, 'Adguard admins']]
        - !Find [authentik_core.group, [name, sa-homepage]]
      is_active: true
      name: sa-homepage
      path: goauthentik.io/service-accounts
      type: service_account
      username: sa-homepage
