---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TALOS_SCRIPTS_DIR: "{{.ROOT_DIR}}/.taskfiles/Talos/scripts"

tasks:
  gen-secrets:
    desc: Generate cluster secrets
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    preconditions:
      - which test talhelper sops
      - test -f {{.TALOS_ROOT}}/bootstrap/talos/talsecret.sops.yaml
      - test -f {{.TALOS_ROOT}}/bootstrap/talos/talconfig.yaml
    # requires:
    #   vars:
    #     - cluster
    vars:
      TALOS_ROOT: "{{.KUBERNETES_ROOT}}/genmachine"
    cmds:
      - talhelper gensecret > {{.TALOS_ROOT}}/bootstrap/talsecret.sops.yaml
      - sops -e -i {{.TALOS_ROOT}}/bootstrap/talsecret.sops.yaml

  bootstrap:
    desc: Bootstrap the cluster
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    requires:
      vars:
        - cluster
    prompt: Bootstrap Talos on the '{{.cluster}}' cluster ... continue?
    cmds:
      - task: generate-config
        vars:
          cluster: "{{.cluster}}"
      - task: apply-config
        vars:
          cluster: "{{.cluster}}"
      - task: bootstrap-etcd
        vars:
          cluster: "{{.cluster}}"
      - task: fetch-kubeconfig
        vars:
          cluster: "{{.cluster}}"
      - until kubectl --context {{.cluster}} --kubeconfig="{{.KUBERNETES_ROOT}}/{{.cluster}}/kubeconfig" wait nodes --for=condition=Ready=False --all --timeout=10m; do sleep 5; done

  #     - task: bootstrap-core
  #       vars:
  #         cluster: "{{.cluster}}"

  generate-config:
    desc: Generate Talos configurations
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    preconditions:
      - which test talhelper cp
      - test -f {{.TALOS_ROOT}}/bootstrap/talos/talsecret.sops.yaml
      - test -f {{.TALOS_ROOT}}/bootstrap/talos/talconfig.yaml
    requires:
      vars:
        - cluster
    vars:
      TALOS_ROOT: "{{.KUBERNETES_ROOT}}/{{.cluster}}"
      TALOS_CONFIG_ROOT: "{{.TALOS_ROOT}}/bootstrap/talos"
    cmds:
      - |
        talhelper genconfig \
          --secret-file {{.TALOS_CONFIG_ROOT}}/talsecret.sops.yaml \
          --config-file {{.TALOS_CONFIG_ROOT}}/talconfig.yaml \
          --out-dir {{.TALOS_CONFIG_ROOT}}/clusterconfig
      - cp {{.TALOS_CONFIG_ROOT}}/clusterconfig/talosconfig {{.TALOS_ROOT}}

  apply-config:
    desc: Apply Talos configurations
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    preconditions:
      - which ls
      - test -f {{.KUBERNETES_ROOT}}/{{.cluster}}/talosconfig
    requires:
      vars:
        - cluster
    vars:
      TALOS_ROOT: "{{.KUBERNETES_ROOT}}/{{.cluster}}"
      TALOS_CONFIG_ROOT: "{{.TALOS_ROOT}}/bootstrap/talos"
      CLUSTER_CONFIG_ROOT: "{{.TALOS_CONFIG_ROOT}}/clusterconfig"
      CONFIG_FILES:
        sh: ls {{.CLUSTER_CONFIG_ROOT}}/*.yaml
      TALOSCONFIG: "{{.TALOS_ROOT}}/talosconfig"
    cmds:
      - for: { var: CONFIG_FILES }
        task: _apply-machineconfig
        vars:
          cluster: "{{.cluster}}"
          FILENAME: "{{.ITEM}}"
          HOSTNAME: |-
            {{ trimPrefix (printf "%s-" .cluster) (base .ITEM) | trimSuffix ".yaml" }}

  _apply-machineconfig:
    internal: true
    desc: Apply a single Talos machineConfig to a Talos node
    preconditions:
      - which talosctl
      - test -f "{{.FILENAME}}"
    requires:
      vars:
        - cluster
        - HOSTNAME
        - FILENAME
    cmds:
      - talosctl apply-config
        --context "{{.cluster}}"
        --nodes "{{.HOSTNAME}}"
        --file "{{.FILENAME}}"
        --insecure

  bootstrap-etcd:
    desc: Bootstrap Etcd
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    preconditions:
      - test -f {{.TALOSCONFIG}}
      - talosctl --context {{.cluster}} config info >/dev/null 2>&1
    requires:
      vars:
        - cluster
    env:
      TALOSCONFIG: "{{.TALOS_ROOT}}/talosconfig"
    vars:
      TALOS_ROOT: "{{.KUBERNETES_ROOT}}/{{.cluster}}"
      TALOS_CONTROLLER:
        sh: talosctl --talosconfig "{{.TALOS_ROOT}}/talosconfig" --context {{.cluster}} config info --output json | jq --raw-output '.endpoints[0]'
    cmds:
      - until talosctl --context {{.cluster}} --nodes {{.TALOS_CONTROLLER}} bootstrap; do sleep 10; done

  fetch-kubeconfig:
    desc: Fetch kubeconfig from Talos controllers
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    preconditions:
      - test -f {{.TALOS_ROOT}}/talosconfig
      - talosctl --context {{.cluster}} config info >/dev/null 2>&1
    requires:
      vars:
        - cluster
    env:
      TALOSCONFIG: "{{.TALOS_ROOT}}/talosconfig"
    vars:
      TALOS_ROOT: "{{.KUBERNETES_ROOT}}/{{.cluster}}"
      KUBECONFIG: "{{.TALOS_ROOT}}/kubeconfig"
      TALOS_CONTROLLER:
        sh: talosctl --talosconfig "{{.TALOS_ROOT}}/talosconfig" --context {{.cluster}} config info --output json | jq --raw-output '.endpoints[0]'
    cmds:
      - talosctl kubeconfig
        --context {{.cluster}}
        --nodes {{.TALOS_CONTROLLER}}
        --force
        --force-context-name {{.cluster}}
        "{{.KUBECONFIG}}"
      - cmd: kubectl config delete-context "admin@{{.cluster}}"
        ignore_error: true