---
spegel:
  image:
    repository: ghcr.io/spegel-org/spegel
    pullPolicy: IfNotPresent
    tag: v0.4.0
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
  spegel:
    containerdRegistryConfigPath: '/etc/cri/conf.d/hosts' # Talos specific config https://spegel.dev/docs/getting-started/#talos
