---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentik-pgsql-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  local:
    path: /home/fred/git/github/ixxeL-GitOps/fullstack/gitops/local-storage/authentik-data/pgsql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fullstack
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentik-redis-data
spec:
  capacity:
    storage: 7Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  local:
    path: /home/fred/git/github/ixxeL-GitOps/fullstack/gitops/local-storage/authentik-data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fullstack
