---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik-redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: local-path-retain
  volumeName: pv-authentik-redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik-pgsql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path-retain
  volumeName: pv-authentik-pgsql-data
