---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fredcorp-wildcard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: fredcorp-wildcard
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: wildcard/fredcorp
        property: cert
    - secretKey: tls.key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: wildcard/fredcorp
        property: key
