---
homepage:
  image:
    registry: ghcr.io
    repository: gethomepage/homepage
    pullPolicy: IfNotPresent
    tag: 'v1.13.1'

  serviceAccount:
    create: true
    automount: true

  rbac:
    enabled: true

  extraEnv:
    - name: HOMEPAGE_FILE_ARGOCD_TOKEN
      value: /app/config/secrets/argocd-token
    - name: HOMEPAGE_FILE_AUTHENTIK_TOKEN
      value: /app/config/secrets/authentik-token
    - name: HOMEPAGE_FILE_ADGUARD_PASSWORD
      value: /app/config/secrets/adguard-password
    - name: HOMEPAGE_FILE_ADGUARD_USER
      value: /app/config/secrets/adguard-user

  volumes:
    - name: homepage-config
      configMap:
        name: homepage-config
    - name: homepage-argocd-token
      secret:
        secretName: homepage-argocd-token
    - name: homepage-authentik-token
      secret:
        secretName: homepage-authentik-token
    - name: homepage-adguard-creds
      secret:
        secretName: homepage-adguard-creds

  volumeMounts:
    - mountPath: /app/config/custom.css
      name: homepage-config
      subPath: custom.css
    - mountPath: /app/config/bookmarks.yaml
      name: homepage-config
      subPath: bookmarks.yaml
    - mountPath: /app/config/docker.yaml
      name: homepage-config
      subPath: docker.yaml
    - mountPath: /app/config/kubernetes.yaml
      name: homepage-config
      subPath: kubernetes.yaml
    - mountPath: /app/config/services.yaml
      name: homepage-config
      subPath: services.yaml
    - mountPath: /app/config/settings.yaml
      name: homepage-config
      subPath: settings.yaml
    - mountPath: /app/config/widgets.yaml
      name: homepage-config
      subPath: widgets.yaml
    - mountPath: /app/config/secrets/argocd-token
      name: homepage-argocd-token
      readOnly: true
      subPath: token
    - mountPath: /app/config/secrets/authentik-token
      name: homepage-authentik-token
      readOnly: true
      subPath: token
    - mountPath: /app/config/secrets/adguard-password
      name: homepage-adguard-creds
      readOnly: true
      subPath: password
    - mountPath: /app/config/secrets/adguard-user
      name: homepage-adguard-creds
      readOnly: true
      subPath: user

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: homepage.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: homepage.talos-genmachine.fredcorp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: homepage-tls-cert
        hosts:
          - homepage.talos-genmachine.fredcorp.com
