---
loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
        admin_api_directory: /var/loki/admin
    rulerConfig:
      storage:
        type: local

    schemaConfig:
      configs:
        - from: '2025-01-01'
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    ruler:
      enable_api: true

  minio:
    enabled: false

  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    persistence:
      enableStatefulSetAutoDeletePVC: true
      enabled: true
      size: 5Gi
      storageClass: nfs-csi-delete

  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0

  gateway:
    enabled: true

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0

alloy:
  controller:
    # -- Type of controller to use for deploying Grafana Alloy in the cluster.
    # Must be one of 'daemonset', 'deployment', or 'statefulset'.
    type: 'daemonset'
    replicas: 1

  crds:
    create: true
  configReloader:
    enabled: false
