---
external-secrets:
  installCRDs: true # try to fix for update v0.16+
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createPushSecret: true
    conversion:
      enabled: true
