---
traefik:
  image:
    registry: docker.io
    repository: traefik
    tag: v3.5.1
    pullPolicy: IfNotPresent

  tlsStore:
    default:
      defaultCertificate:
        secretName: k0s-fullstack-wildcard

  service:
    loadBalancerIP: '192.168.1.191'
