---
traefik:
  image:
    registry: docker.io
    repository: traefik
    tag: v3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
    pullPolicy: IfNotPresent

  tlsStore:
    default:
      defaultCertificate:
        secretName: k0s-fullstack-wildcard
