---
traefik:
  image:
    registry: docker.io
    repository: traefik
    tag: v3.3.3@sha256:19884a9d0b922b321c9cff54cbfe43f3169893041b8dd4ea6100677afaddce46
    pullPolicy: IfNotPresent

  tlsStore:
    default:
      defaultCertificate:
        secretName: k0s-fullstack-wildcard

  ingressRoute:
    dashboard:
      enabled: false
      annotations: {}
      labels: {}
      matchRule: Host(`traefik.k0s-fullstack.fredcorp.com`)
      middlewares:
        - name: authentik
          namespace: authentik
      services:
        - name: api@internal
          kind: TraefikService
      entryPoints: [web, websecure]
      tls: {}
