---
crowdsec:
  container_runtime: containerd
  lapi:
    enabled: true
    env:
    - name: ENROLL_KEY
      value: Pr6YK7BcflVk91WVAkjn
    - name: ENROLL_INSTANCE_NAME
      value: fullstack
    - name: ENROLL_TAGS
      value: k8s linux test
    ingress:
      enabled: true
      ingressClassName: traefik
      host: crowdsec.k0s-fullstack.fredcorp.com
    persistentVolume:
      data:
        enabled: true
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path-delete
        existingClaim: ''
        size: 1Gi
      config:
        enabled: true
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path-delete
        existingClaim: ''
        size: 100Mi

  dashboard:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      host: crowdsec-meta.k0s-fullstack.fredcorp.com

  agent:
    enabled: true
    isDeployment: false
    acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
    env:
    - name: COLLECTIONS
      value: crowdsecurity/traefik

  # -- Enable AppSec (https://docs.crowdsec.net/docs/next/appsec/intro)
  appsec:
    enabled: false
