---
spegel:
  priorityClassName: system-node-critical
  spegel:
    logLevel: 'INFO'
    registries:
      - https://cgr.dev
      - https://docker.io
      - https://ghcr.io
      - https://quay.io
      - https://mcr.microsoft.com
      - https://public.ecr.aws
      - https://gcr.io
      - https://registry.k8s.io
      - https://k8s.gcr.io
      - https://lscr.io
