---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: fullstack
  user: admin
spec:
  hosts:
  - role: single
    installFlags:
    - --debug
    - --disable-components=autopilot,helm,windows-node,konnectivity-server
    ssh:
      address: 192.168.1.190
      user: fred
      port: 22
      keyPath: ~/.ssh/id_rsa
    uploadBinary: false
    hostname: k0s-fullstack
    dataDir: /var/lib/k0s
  k0s:
    version: v1.32.1+k0s.0
    versionChannel: stable 
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s-fredcorp
      spec:
        storage:
          type: kine
        telemetry:
          enabled: false
        api:
          address: 192.168.1.190
          port: 6443
          k0sApiPort: 9443
          sans:
          - 192.168.1.190
          externalAddress: k0s.fullstack.fredcorp.com
        network:
          provider: kuberouter
          clusterDomain: cluster.local
          kuberouter:
            autoMTU: true
            hairpin: Enabled
          kubeProxy:
            disabled: false
            mode: iptables
        controllerManager: {}
        scheduler: {}
        extensions: {}
