adguard-home:
  image:
    repository: adguard/adguardhome
    pullPolicy: Always
    tag: "v0.107.56"

  services:
    adminPanel:
      type: ClusterIP
      port: 3000
    http:
      type: ClusterIP
      port: 80
    https:
      enabled: true
      type: ClusterIP
      port: 443
    dns:
      enabled: true
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: "172.18.0.2-ip"
      externalTrafficPolicy: Local
      # loadBalancerIP: 172.18.0.2
      tcp:
        port: 53
        nodePort:
      udp:
        port: 53
        nodePort:
    dnsOverTls:
      enabled: true
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: "172.18.0.2-ip"
      externalTrafficPolicy: Local
      # loadBalancerIP: 172.18.0.2
      port: 853
    dnsOverQuic:
      enabled: true
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: "172.18.0.2-ip"
      port1:
        port: 784
        nodePort:
      port2:
        port: 8853
        nodePort:
      externalTrafficPolicy: Local
      # loadBalancerIP: 172.18.0.2
    dnscrypt:
      enabled: false
      type: LoadBalancer
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: "172.18.0.2-ip"
      externalTrafficPolicy: Local
      # loadBalancerIP: 172.18.0.2
      tcp:
        port: 5443
        nodePort:
      udp:
        port: 5443
        nodePort:

  ingresses:
    adminPanel:
      enabled: true
      className: "traefik"
      hosts:
        - host: adguard-admin.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: adguard-admin-tls
      #    hosts:
      #      - adguard-admin.k0s-fullstack.fredcorp.com
    http:
      enabled: true
      className: "traefik"
      hosts:
        - host: adguard.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - adguard.k0s-fullstack.fredcorp.com
    https:
      enabled: true
      className: "traefik"
      hosts:
        - host: adguard-secure.k0s-fullstack.fredcorp.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: adguard-secure-tls
      #    hosts:
      #      - adguard-secure.k0s-fullstack.fredcorp.com

  persistence:
    existingClaim: pvc-adguard-data
    volumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  bootstrapEnabled: false