---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-k0s-0
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-retain
  volumeName: pv-vault-data
