---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
resources:
- https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
- sc-retain.yaml
patches:
  - target:
      kind: ConfigMap
      name: local-path-config
      namespace: local-path-storage
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: local-path-config
        namespace: local-path-storage
      data:
        config.json: |-
          {
              "nodePathMap":[
              {
                      "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                      "paths":["/home/fred/git/github/ixxeL-GitOps/fullstack/gitops/local-storage"]
              }
              ]
          }
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: replace
        path: /metadata/name
        value: local-path-delete
