---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  all:
    - task: markdown
    - task: yaml

  markdown:
    desc: Format Markdown
    cmds:
      - >-
        prettier --config '.prettierrc.json' --ignore-path '.prettierignore' --list-different --ignore-unknown --parser=markdown --write '*.md' '**/*.md'
    ignore_error: true

  yaml:
    desc: Format YAML
    cmds:
      - >-
        prettier --config '.prettierrc.json' --ignore-path '.prettierignore' --list-different --ignore-unknown --parser=yaml --write '*.y*ml' '**/*.y*ml'
    ignore_error: true
