---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: adguard
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../common
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/adguard/*'
            exclude: false
          - path: 'gitops/manifests/adguard/common'
            exclude: true
          - path: 'gitops/manifests/adguard/beelink'
            exclude: true
  template:
    metadata:
      name: 'adguard-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../common
    spec:
      project: infra-network
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: adguard
      sources:
        - path: 'gitops/manifests/adguard/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: adguard
            valueFiles:
              - $values/gitops/manifests/adguard/common/common-values.yaml
              - $values/gitops/manifests/adguard/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 2m
        managedNamespaceMetadata:
          annotations:
            volsync.backube/privileged-movers: 'true'
          labels:
            bundle.chain/inject: 'enabled'
