---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /gitops/core/apps/genmachine;/gitops/core/appProjects;/gitops/core/repos;/gitops/core/clusters/genmachine
    argocd-diff-preview/watch-pattern: 'gitops/core/.*'
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  sources:
    - path: gitops/core/apps/genmachine
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/appProjects
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/repos
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
    - path: gitops/core/clusters/genmachine
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 4
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
