---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gha-arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/gha-arc-controller/*'
            exclude: false
          - path: 'gitops/manifests/gha-arc-controller/values'
            exclude: true
          - path: 'gitops/manifests/gha-arc-controller/beelink'
            exclude: true
          - path: 'gitops/manifests/gha-arc-controller/k0s'
            exclude: true
  template:
    metadata:
      name: 'gha-arc-controller-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values
    spec:
      project: infra-security
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: arc-system
      sources:
        - path: 'gitops/manifests/gha-arc-controller/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: gha-arc-controller
            valueFiles:
              - $values/gitops/manifests/gha-arc-controller/values/common-values.yaml
              - $values/gitops/manifests/gha-arc-controller/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 4
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
        managedNamespaceMetadata:
          labels:
            bundle.chain/inject: 'enabled'
