---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8up
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../../values;../crd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/k8up/*'
            exclude: false
          - path: 'gitops/manifests/k8up/values'
            exclude: true
          - path: 'gitops/manifests/k8up/beelink'
            exclude: true
  template:
    metadata:
      name: 'k8up-{{ index .path.segments 3 }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../../values;../crd
    spec:
      project: infra-storage
      destination:
        name: '{{ index .path.segments 3 }}'
        namespace: k8up
      sources:
        - path: 'gitops/manifests/k8up/{{ index .path.segments 3 }}/app'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: k8up
            valueFiles:
              - $values/gitops/manifests/k8up/values/common-values.yaml
              - $values/gitops/manifests/k8up/{{ index .path.segments 3 }}/app/{{ index .path.segments 3 }}-values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
        - path: gitops/manifests/k8up/{{ index .path.segments 3 }}/crd
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 2m
