---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/kyverno/*'
            exclude: false
          - path: 'gitops/manifests/kyverno/values'
            exclude: true
          - path: 'gitops/manifests/kyverno/beelink'
            exclude: true
          - path: 'gitops/manifests/kyverno/k0s'
            exclude: true
  template:
    metadata:
      name: 'kyverno-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values
    spec:
      project: infra-network
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: kyverno
      sources:
        - path: 'gitops/manifests/kyverno/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: kyverno
            valueFiles:
              - $values/gitops/manifests/kyverno/values/common-values.yaml
              - $values/gitops/manifests/kyverno/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 4
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
