---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/nginx-ingress/*'
            exclude: false
          - path: 'gitops/manifests/nginx-ingress/values'
            exclude: true
          - path: 'gitops/manifests/nginx-ingress/beelink'
            exclude: true
          - path: 'gitops/manifests/nginx-ingress/k0s'
            exclude: true
  template:
    metadata:
      name: 'nginx-ingress-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values
    spec:
      project: infra-security
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: nginx-ingress
      sources:
        - path: 'gitops/manifests/nginx-ingress/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            valueFiles:
              - $values/gitops/manifests/nginx-ingress/values/common-values.yaml
              - $values/gitops/manifests/nginx-ingress/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
