---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: popeye
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/popeye/*'
            exclude: false
  template:
    metadata:
      name: 'popeye-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: infra-monitoring
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: popeye
      source:
        path: 'gitops/manifests/popeye/{{ .path.basenameNormalized }}'
        repoURL: https://github.com/ixxeL-DevOps/fullstack.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 4
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
