---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/ixxeL-DevOps/fullstack.git'
        revision: main
        directories:
          - path: 'gitops/manifests/proxmox-csi-plugin/*'
            exclude: false
          - path: 'gitops/manifests/proxmox-csi-plugin/values'
            exclude: true
          - path: 'gitops/manifests/proxmox-csi-plugin/beelink'
            exclude: true
          - path: 'gitops/manifests/proxmox-csi-plugin/k0s'
            exclude: true
  template:
    metadata:
      name: 'proxmox-csi-plugin-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;../values
    spec:
      project: infra-storage
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: proxmox-csi-plugin
      sources:
        - path: 'gitops/manifests/proxmox-csi-plugin/{{ .path.basenameNormalized }}'
          repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          helm:
            releaseName: proxmox-csi-plugin
            valueFiles:
              - $values/gitops/manifests/proxmox-csi-plugin/values/common-values.yaml
              - $values/gitops/manifests/proxmox-csi-plugin/{{ .path.basenameNormalized }}/{{ .path.basenameNormalized }}-values.yaml
        - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
