---
name: Auto create PR for Hydrator
on:
  push:
    branches:
    - 'deploy/k0s-preview'
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  auto-pr-hydrator:
    name: Create PR to deploy k0s
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: pull-request
      run: |
        echo -e "${BLUE}[ STEP - CREATING PR ] > Creatin Pull Request with gh CLI${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        gh_pr_up() {
          gh pr create "$@" || gh pr edit "$@" 
        }

        gh_pr_up --title "chore(hydrator): deploying into deploy/k0s" \
                 --body ":crown: *An automated PR* - ${{ github.ref }}" \
                 --base "deploy/k0s"
      env:
        GH_TOKEN: ${{ secrets.SUPER_ADMIN_TOKEN }}
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m