---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-k0s
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: infra-security
  source:
    path: k0s-home/manifests/external-secrets
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true