---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-headscale-data
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  local:
    path: /home/fred/git/github/ixxeL-GitOps/fullstack/gitops/local-storage/headscale-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fullstack
