---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-headscale-data
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-retain
  volumeName: pv-headscale-data
