---
apiVersion: v1
kind: Service
metadata:
  name: headscale-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app.kubernetes.io/instance: headscale
    app.kubernetes.io/name: headscale
