    # It's suggested to use environment variables to configure Headscale.
    # For config reference, see https://github.com/juanfont/headscale/blob/main/config-example.yaml
    # To configure any of these as an env:
    #   1. Flatten object keys using "_"
    #   2. Prefix with "HEADSCALE_"
    #
    # For example:
    #   - "listen_addr" becomes "HEADSCALE_LISTEN_ADDR"
    #   - "log.level" becomes "HEADSCALE_LOG_LEVEL"
