---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volsync-bakckup
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.1.250
      share: /volatile
      subdir: volsync-genmachine-backup
    volumeHandle: 192.168.1.250#volatile#volsync-genmachine-backup##
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
