---
kube-prometheus-stack:
  prometheusOperator:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-operator
      tag: v0.82.0
      pullPolicy: IfNotPresent

  prometheus:
    enabled: true
    prometheusSpec:
      image:
        registry: quay.io
        repository: prometheus/prometheus
        tag: v3.3.0
      retention: 7d
      scrapeInterval: '30s'
      logLevel: info
      serviceMonitorSelector:
        matchLabels:
          release: 'prometheus'
      podMonitorSelector:
        matchLabels:
          release: 'prometheus'

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: prometheus.talos-genmachine.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
      ingressClassName: traefik
      pathType: Prefix
      hosts:
        - prometheus.talos-genmachine.fredcorp.com
      path: /
      tls:
        - hosts:
            - prometheus.talos-genmachine.fredcorp.com
          secretName: prometheus-tls-cert
  grafana:
    image:
      registry: docker.io
      repository: grafana/grafana
      tag: '11.6.1'
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: fredcorp-ca
        cert-manager.io/common-name: grafana.talos-genmachine.fredcorp.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.scheme: https
      ingressClassName: traefik
      hosts:
        - grafana.talos-genmachine.fredcorp.com
      path: /
      tls:
        - hosts:
            - grafana.talos-genmachine.fredcorp.com
          secretName: grafana-tls-cert

prometheus-blackbox-exporter:
  ingress:
    enabled: true
    className: 'traefik'
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: blackbox.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    hosts:
      - host: blackbox.talos-genmachine.fredcorp.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - blackbox.talos-genmachine.fredcorp.com
        secretName: blackbox-tls-cert

prometheus-pushgateway:
  image:
    repository: quay.io/prometheus/pushgateway
    tag: v1.11.1
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: 'traefik'
    annotations:
      cert-manager.io/cluster-issuer: fredcorp-ca
      cert-manager.io/common-name: push-gateway.talos-genmachine.fredcorp.com
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/service.scheme: https
    hosts:
      - push-gateway.talos-genmachine.fredcorp.com
    tls:
      - hosts:
          - push-gateway.talos-genmachine.fredcorp.com
        secretName: push-gateway-tls-cert
  serviceMonitor:
    enabled: true
    namespace: prometheus
    additionalLabels:
      release: prometheus
