---
headscale:
  persistence:
    # -- Configure persistence settings for the chart under this key.
    # @default -- See [values.yaml](./values.yaml)
    config:
      enabled: true
      mountPath: /etc/headscale
      retain: false
      storageClass: 'local-path-delete'

  env:
    # -- Defines the base domain to create the hostnames for MagicDNS.
    # This domain _must_ be different from the server_url domain.
    HEADSCALE_DNS_BASE_DOMAIN: '.wireguard.fredcorp.com'

    # HEADSCALE_OIDC_ISSUER: ""
    # HEADSCALE_OIDC_CLIENT_ID: ""
    # HEADSCALE_OIDC_CLIENT_SECRET: ""

    # -- Node IPv4 prefixes
    HEADSCALE_PREFIXES_V4: '100.64.0.0/10'
    # -- Node IPv6 prefixes
    HEADSCALE_PREFIXES_V6: 'fd7a:115c:a1e0::/48'

    # -- List of DNS servers to expose to clients.
    HEADSCALE_DNS_NAMESERVERS_GLOBAL: '192.168.1.200 1.1.1.1'
    # -- Whether to use [MagicDNS](https://tailscale.com/kb/1081/magicdns/).
    HEADSCALE_DNS_MAGIC_DNS: 'true'

    HEADSCALE_DERP_URLS: 'https://controlplane.tailscale.com/derpmap/default'
    HEADSCALE_DERP_AUTO_UPDATE_ENABLED: 'true'
    HEADSCALE_DERP_UPDATE_FREQUENCY: '24h'

    HEADSCALE_EPHEMERAL_NODE_INACTIVITY_TIMEOUT: '30m'
    HEADSCALE_LOG_LEVEL: 'debug'
    HEADSCALE_DISABLE_CHECK_UPDATES: 'true'

  sidecars:
    ui:
      image: ghcr.io/gurucomputing/headscale-ui:latest
      ports:
        - name: http
          containerPort: 80

  service:
    main:
      ports:
        ui:
          port: 80

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See [values.yaml](./values.yaml)
    ui:
      enabled: true
      hosts:
        - host: headscale.k0s-fullstack.fredcorp.com
          paths:
            - path: /web
              service:
                port: 80
      tls:
        - hosts:
            - headscale.k0s-fullstack.fredcorp.com

    # main:
    #   enabled: true
    #   hosts:
    #     - host: headscale-main.k0s-fullstack.fredcorp.com
    #       paths:
    #         - path: /
    #   tls:
    #     - hosts:
    #         - headscale-main.k0s-fullstack.fredcorp.com
