---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: fredcorp-ca-chain
spec:
  sources:
    - useDefaultCAs: false
    - secret:
        name: 'root-ca-chain'
        includeAllKeys: true
  target:
    secret:
      key: 'fredcorp-ca-chain.pem'
    additionalFormats:
      pkcs12:
        key: 'fredcorp-ca-chain.p12'
        password: ''
