reloader:
  image:
    name: stakater/reloader
    repository: ghcr.io/stakater/reloader
    tag: v1.3.0@sha256:61e2cd350a366059b19d922badfd2a1b35a3f5ee7b872c43d9853c27387637fb
    pullPolicy: IfNotPresent
