---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-operator-github
  namespace: renovate-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: renovate-operator-github
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-operator/github/genmachine
        property: token
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        key: renovate-operator/github/genmachine
        property: token
