---
# 1. fetch GitHub App Private Key from Secrets Manager
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: github-app-pem
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: github/gh-app/ixxel-devops/pipelines
        property: PRIVATE_KEY
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
---
# 2. create a GithubAccessToken using GitHub App Credentials
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "1156216"
  installID: "61577324"
  auth:
    privateKey:
      secretRef:
        name: github-app-pem
        key: private_key_pem
---
# 3. create a secret containing the required keys
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "45m0s"
  target:
    name: renovate-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template: # template secret to use  GITHUB_COM_TOKEN
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN:  "{{`{{ .token }}`}}"
        GITHUB_COM_USER: "ixxeL2097" # base64 encoded GH username
        RENOVATE_TOKEN: "{{`{{ .token }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
