# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Argo CD Diff Preview
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  argocd-diff-preview:
    runs-on: fredcorp
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@30bf6253fa41bdc8d1501d202ad15287582246b4 # v2.0.3
        id: app-token
        with:
          app-id: ${{ secrets.GHAPP_APP_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            **/Chart.yaml
            **/Chart.yml
            **/*values.yaml
            **/*values.yml

      - name: Checkout PR path
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          path: pull-request
          token: ${{ steps.app-token.outputs.token }}

      - name: Checkout main path
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          ref: main
          path: main
          token: ${{ steps.app-token.outputs.token }}

      - name: Generate Diff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            -e FILES_CHANGED="${{ steps.changed-files.outputs.all_changed_files }}" \
            dagandersen/argocd-diff-preview:v0.1.1 --debug

      - name: Post diff as comment
        if: steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
