# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Argo CD Diff Preview
on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  argocd-diff-preview:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45
        with:
          files: |
            gitops/manifests/**
            gitops/core/**
            gitops/bootstrap/**

      - name: GH App get Token
        id: get-app-token
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GHAPP_APP_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          path: pull-request
          token: ${{ steps.get-app-token.outputs.token }}

      - uses: actions/checkout@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          ref: main
          path: main
          token: ${{ steps.get-app-token.outputs.token }}

      - name: Generate Diff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            -e FILES_CHANGED="${{ steps.changed-files.outputs.all_changed_files }}" \
            dagandersen/argocd-diff-preview:v0.0.35

      - name: Post diff as comment
        if: steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
