# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Auto create PR for Hydrator
on:
  push:
    branches:
      - deploy/k0s-preview
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  auto-pr-hydrator:
    name: Create PR to deploy k0s
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: app-token
        with:
          app-id: ${{ secrets.GHAPP_APP_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 0

      - name: pull-request
        run: |
          echo -e "${BLUE}[ STEP - CREATING PR ] > Creatin Pull Request with gh CLI${BLANK}"
          echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
          gh --version

          gh_pr_up() {
            gh pr create "$@" || gh pr edit "$@"
          }

          gh_pr_up --title "chore(hydrator): deploying into deploy/k0s" \
                   --body ":crown: *An automated PR* - ${{ github.ref }}" \
                   --base "deploy/k0s"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.TOKEN }}
          RED: \033[1;31m
          GREEN: \033[1;32m
          YELLOW: \033[1;33m
          BLUE: \033[1;34m
          PURPLE: \033[1;35m
          CYAN: \033[1;36m
          BLANK: \033[0m
