# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Kustomize Dynamic Rendered Manifest
on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**/kustomization.yaml'
      - '**/kustomization.yml'

concurrency:
  group: ${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  rendered-manifest:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.GHAPP_APP_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: '${{ steps.app-token.outputs.token }}'
          fetch-depth: 0

      - name: Find modified Kustomization.yaml files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            **/kustomization.yaml
            **/kustomization.yml

      - name: Generate diffs for each Kustomization
        id: gen-pr-kustomize
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "KUSTOMIZATION_FILES=${ALL_CHANGED_FILES}"
          UNIQ_PATHS_CHANGED=$(echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | grep -v '^$' | awk -F/ '{if (NF > 1) {NF--; print $0}}' OFS='/' | sort -u)
          echo "UNIQ_PATHS_CHANGED=$UNIQ_PATHS_CHANGED"
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin && chmod +x /usr/local/bin/kustomize

          template() {
            local suffix=$1
            mkdir -p $suffix
            base=$(basename "$path")
            kustomize build "$path" > "${suffix}/${base}_manifest_${suffix}.yaml"
          }

          for path in ${UNIQ_PATHS_CHANGED}; do
            echo "Processing path: ${path}"

            template "pr"

            git checkout origin/main -- "$path"

            template "main"
            echo ""
          done

      - name: Generate dyff on release
        id: dyff-helm
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ixxeL-DevOps/gha-templates/.github/actions/dyff@main
        with:
          source: main/*_manifest_main.yaml
          target: pr/*_manifest_pr.yaml
          exclude-regexp: spec.template.metadata.annotations.checksum

      - name: Generate diff on release
        id: diff-helm
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ixxeL-DevOps/gha-templates/.github/actions/diff@main
        with:
          source: main/*_manifest_main.yaml
          target: pr/*_manifest_pr.yaml

      - name: Post diff as comment
        if: steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file diff.md
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.TOKEN }}

      - name: Kubeconform
        id: kubeconform
        if: steps.changed-files.outputs.any_changed == 'true'
        continue-on-error: true
        uses: ixxeL-DevOps/gha-templates/.github/actions/kubeconform@main
        with:
          target: pr
