---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  repository_dispatch:
    types:
      - renovate
  schedule:
    - cron: 0 2 * * *
    - cron: 0 3 * * *

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        id: clone
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-clone@main
        with:
          mode: 'app'
          app-id: ${{ secrets.GHAPP_APP_ID }}
          private-key: ${{ secrets.GHAPP_PRIVATE_KEY }}

      - name: Run Renovate
        uses: renovatebot/github-action@08ed9fa83e24bfe6222557f9e221395c57972127 # v41.0.16
        with:
          token: ${{ steps.clone.outputs.TOKEN }}
          docker-volumes: |
            ${{ github.workspace }}/.npmrc:/github-action/.npmrc
          env-regex: ^(?:RENOVATE_\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|NODE_TLS_REJECT_UNAUTHORIZED|NPM_CONFIG_USERCONFIG)$
        env:
          LOG_LEVEL: debug
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          NPM_CONFIG_USERCONFIG: /github-action/.npmrc
