---
k8up:
  image:
    pullPolicy: IfNotPresent
    registry: ghcr.io
    repository: k8up-io/k8up
    tag: v2.12.0

  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
