---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd-diff-preview/watch-pattern: 'gitops/manifests/adguard/.*'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  project: infra-network
  source:
    path: gitops/manifests/adguard
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
