---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-k0s
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: infra-security
  source:
    path: gitops/manifests/external-secrets
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
  # sourceHydrator:
  #   drySource:
  #     repoURL: https://github.com/ixxeL-DevOps/fullstack.git
  #     path: gitops/manifests/external-secrets
  #     targetRevision: main
  #   syncSource:
  #     targetBranch: deploy/k0s
  #     path: gitops/manifests/external-secrets
  # hydrateTo:
  #   targetBranch: deploy/k0s-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
