---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-k0s
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../values
    argocd-diff-preview/watch-pattern: 'gitops/manifests/uptime-kuma/k0s/.*, gitops/manifests/uptime-kuma/values/.*'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  project: infra-monitoring
  sources:
    - path: gitops/manifests/uptime-kuma/k0s
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      helm:
        valueFiles:
          - $values/gitops/manifests/uptime-kuma/values/common-values.yaml
          - $values/gitops/manifests/uptime-kuma/k0s/k0s-values.yaml
    - repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
