---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-k0s
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: infra-security
  source:
    path: gitops/manifests/vault
    repoURL: https://github.com/ixxeL-DevOps/fullstack.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates
