---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard-k0s
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  project: infra-security
  sourceHydrator:
    drySource:
      repoURL: https://github.com/ixxeL-DevOps/fullstack.git
      path: gitops/manifests/wireguard
      targetRevision: main
    syncSource:
      targetBranch: deploy/k0s
      path: gitops/manifests/wireguard
    # hydrateTo:
    #   targetBranch: deploy/k0s-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - PruneLast=false
    - RespectIgnoreDifferences=true
    - Replace=false
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - ServerSideApply=true
