# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: InvitationFlow
entries:
  - model: authentik_stages_invitation.invitationstage
    attrs:
      name: invite
    identifiers:
      name: invite
